---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30s
  path: ./apps
  prune: true
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
  patches:
    # Used to keep kustomizations DRY that require decryption and substitution variables
    # TODO: Consider if there are use cases where decryption is used but not substitution and vice versa, if so split this into two separate optional patches
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-gpg
          postBuild:
            substituteFrom:
              - kind: Secret
                name: cluster-secrets
              - kind: ConfigMap
                name: cluster-config
      target:
        labelSelector: substitution.flux/enabled=true
