apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
type: Opaque
stringData:
    ADD_BOT_TOKEN: ENC[AES256_GCM,data:VKKKrsjikURszsjGguN7FEZrbFesz0cskAUdVBGdCEUtW1yS0xXN7ljeHO5XRg==,iv:i9m4b7h5q9FO5NWb2+UmMBVIluYeWb5SyBTG0tO+62I=,tag:9aNSzAiNYzgS1xqbJsdeMA==,type:str]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:K2KUt2c6/7MVwdZZ3LpOUtaD,iv:xRsYd123r+iaRWYGjiK9k7ck1cyj0/7Hsu45USI7xI0=,tag:/s9Fzg6Xa6eft5Vs5yHNzw==,type:str]
    FLUX_NOTIFICATION_DOMAIN_NAME: ENC[AES256_GCM,data:BAsEqFzst4MAqKHtnDdohEw7gRPjw5qzDa3Heyu9,iv:+r4x3MFGUtffeCDbSjbpum+OeOs7xYBnMTflSildT/8=,tag:GaVMb7qvqo1I03ihh6Mk2Q==,type:str]
    PODINFO_DOMAIN_NAME: ENC[AES256_GCM,data:ZX10MXxeuiWWnA3ZBxY/aot6J0E=,iv:Rz5adZg/Nhg8Ab0zFuwmvj79z2GfSHGcDfNA01yTV+k=,tag:z+jqorbvLNggMO8Oxj7tCg==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:e8GR4kogxXplJK/67S0QR4q6,iv:c0Eui6/XzSJZGttmafZdvNjlSqULc7abVCr2TGeJHX0=,tag:Hd0mEKqOowBqPsqQ4Gpu9A==,type:str]
    EXTERNAL_DNS_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:DRswXksY/LW6VCUA0BZgPG0rDPxu0oBbQ7Bm6BOSgm/GPpC6cceJLA==,iv:XBtP2+/xEm2QDhAEIDohTsES/BqwQ7C4Lhn679whIYk=,tag:yeOS0rW37CE4f8+WTdd4nQ==,type:str]
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:Kn4Ht5JJ9IFBhPKE4bKqPXpZ/rdqiuPs83mLb9Te/SssIrCxCFG8/pcsf/sPdNyK1n+dLXf3guPzTOp3+MIa0qZ8NEJU7znplUTPTydHRrkJQXBcwcPMlA==,iv:WBzjOK8tleimkx9LFc6ktrjJWAhU6USo9NKylqYcbKs=,tag:jUQEqU6Dzh/fxwUC4VciIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-01T14:22:45Z"
    mac: ENC[AES256_GCM,data:lcQOJ0jL261CqnlVduFtMAQ6bWsYT/t55C4Mo/sTB7jAAbfRT+UyNwNmODdLCFbqufMQa8+KtTXLbkiDOKAO9kEjNd8XHCQ3SnmO6hSgTSAKohMYoQFuna7bqMyXVvIlsBmvXpvLTP3Kklnm+snGWsq94g2BCrlzQpfFaDufSz8=,iv:+hPfH8J1RxWT7KXY7jmcKr1jxD5VSJEU9YKY+GGFGn4=,tag:x35lJ08+TycV9UdV39Cy1g==,type:str]
    pgp:
        - created_at: "2023-04-11T10:46:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8WjeZLD+fxwAQ/+Nq6Ca1EZPPKJL623l80q3bBdEBNGsW+5fzLHvxN1w3ro
            spWiuwAnANGywTff2Ado+itLKiYnwnXigj+H+jkjvbvmvWUMr2xSWKKdNes6BRaC
            bZbQ99U2Egr9LHAMGFdPjwaVXPbPaJ3NGCusl1FV3Qufc6PQvdcJHONdyGzG2TDa
            iRn/Qe4KakHt+ox0CQW8MaNfoCWVRsImSWkpL//yIDoRiNFPcTEg4RgqSVMudKeJ
            LcAhFzyAmiHUm2AP8mCuYCN6T1hkQLHuxFLhyFF9PCy/ap/FUWuiRSg0rsDYZwQP
            vaPSylggZk3mst22vCSlCualIJYXzq7cQv+lrZ36xD3w4Z6sUUZ/rGNTAM9Pb1cB
            cuU+Gc2561DtmxIkkmTv7u3K1YCZTBqUGO6Y1cr+mVtzyhyvl7hctGL5ZYuFlHvJ
            eDzVa7eZp2k5LhR7PbNvt5Gv/U0xp9Xfb/li/7glWGwhc/iZYFI8f1/xpKzjAbTN
            ckG6p2002r/FBdJWtL2jwc3CyAj9u6I5UvSZoD2RHdWHlJjqvCULMXOWcHiMZ1qt
            Isv6TRRzQPhBfzxKUs9k1l/Aw8VGqxMBpeCBcbvFHib/Dd/stm2hsE+AsslebPpm
            odBpI+S+oZYaNYtKU/TrysH4iV5t6vJLBkBUQGVaGu2mVWFPMZfxXiL1uBALefXS
            UQE8PPXp1DI1Rp7zEIlrQ3VU3tYha0lgQCe8sKJT/QG+bo6ZFib1EQuh4pylLwa3
            ipmxhH1xM/CHFBvB1pcZ4cczpDx3zInJ60sOisSzE7L97Q==
            =M7Qy
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
