apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: add-bot
spec:
  interval: 24h
  timeout: 3m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/add-bot
  prune: true
  wait: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
