apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: navidrome
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/navidrome
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
