---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gonic-music
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nectarine.internal.fruitiex.org/volume3/music/Rasmus#gonic-music
    volumeAttributes:
      server: nectarine.internal.fruitiex.org
      share: /volume3
      subDir: music/Rasmus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gonic-music
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-gonic-music
  storageClassName: nfs-csi
