---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gonic-music-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nectarine.internal.fruitiex.org/volume3/music#gonic-music
    volumeAttributes:
      server: nectarine.internal.fruitiex.org
      share: /volume3
      subDir: music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gonic-music-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: gonic-music-pv
  storageClassName: nfs-csi
