apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  interval: 24h
  timeout: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: false
    alertmanager:
      service:
        type: NodePort
      ingress:
        enabled: true
        ingressClassName: private
        tls:
          - secretName: fruitiex-org-tls
        hosts:
          - alertmanager.fruitiex.org
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: syno-storage
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
    prometheus:
      service:
        type: NodePort
      ingress:
        enabled: true
        ingressClassName: private
        tls:
          - secretName: fruitiex-org-tls
        hosts:
          - prometheus.fruitiex.org
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: syno-storage
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
