apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  interval: 10m
  timeout: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      service:
        type: NodePort
      ingress:
        enabled: true
        ingressClassName: private
        tls:
          - secretName: fruitiex-org-tls
        hosts:
          - grafana.fruitiex.org
    alertmanager:
      service:
        type: NodePort
      ingress:
        enabled: true
        ingressClassName: private
        tls:
          - secretName: fruitiex-org-tls
        hosts:
          - alertmanager.fruitiex.org
    prometheus:
      service:
        type: NodePort
      ingress:
        enabled: true
        ingressClassName: private
        tls:
          - secretName: fruitiex-org-tls
        hosts:
          - prometheus.fruitiex.org
