# https://cert-manager.io/docs/tutorials/acme/nginx-ingress/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - cloudflare-api-token-secret.yaml
  - namespace.yaml
  - release.yaml