apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
spec:
  interval: 1h
  timeout: 3m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/crds
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager
    - name: metallb
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: metallb-controller
  #     namespace: metallb
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
