apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - sources.yaml
  - cert-manager.yaml
  - notification-receiver.yaml
  - notification-provider.yaml
  - synology-csi.yaml
  - csi-driver-nfs.yaml
  - crds.yaml
  - kube-prometheus-stack.yaml
  - external-dns.yaml
  - ingress-nginx-public.yaml
  - ingress-nginx-private.yaml
  - metallb.yaml
  - reloader.yaml
  - reflector.yaml
  - influxdb.yaml
  - grafana.yaml
  # - loki-stack.yaml
  # - nfs-subdir-external-provisioner.yaml