apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - sources.yaml
  - cert-manager.yaml
  - notification-receiver.yaml
  - notification-provider.yaml
  - nfs-subdir-external-provisioner.yaml
  - synology-csi.yaml
  - crds.yaml
  - kube-prometheus-stack.yaml
  - external-dns.yaml
  - ingress-nginx-public.yaml
  - ingress-nginx-private.yaml
  - metallb.yaml
  - pihole.yaml
  - reloader.yaml