apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
spec:
  interval: 1h
  timeout: 1m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/networking/metallb
  prune: true
  wait: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
