apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: notification-receiver
spec:
  interval: 99999h
  timeout: 3m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/flux/notification-receiver
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
