apiVersion: v1
kind: Secret
metadata:
    name: littlewardrobe-server-env
type: Opaque
stringData:
    LITTLEWARDROBE_SETUP_TOKEN: ENC[AES256_GCM,data:RqktH8pVtVY5IeqxMfJlaQ7mqYk+vcuq+n3UMkBs6F9rCWbKK9vV1BqpLXeQ5VgHzUyERLa84dUnTn5M3Ey9ZA==,iv:T8yjEYb9pWIi1vbGtYLYUCygGFLF5B2WhtzHnXcTfaw=,tag:2X3DdZ1/AIUMbnHQ6SMojw==,type:str]
    LITTLEWARDROBE_SECRET_KEY: ENC[AES256_GCM,data:5BRD9IXa59BCyfuSNwF0xFxjTBV++1NcRCZSVNe84thkgkvpRFRWDN/E9Qv4cGqfbRpzLiTHm0HYtn8XEQjn5w==,iv:ySIg/zgY4bZQSQ4T55zHekNzDNCrGlS4IRlpAssNFPw=,tag:sRd6i7R1SpVXu2GFt/6LAw==,type:str]
sops:
    lastmodified: "2026-10-02T05:20:00Z"
    mac: ENC[AES256_GCM,data:ClMmLbfgMSsOdITwPbavbcJOZzmfGYWpija8GrqsVc5dUhfOWBajpFhMNe+SO+vZgPOTGb4sskxe2i3QPeTGUBDtNRm77AnEXwBvKhSiXyUavR765yHSdASd2J4Nzip8iVExPQ7qd0F0qzj1TP35BhaPmYkt1PiK8djWadskEUg=,iv:UcsrarhZQeP7LgCAlxCSEkpKq267diqgsiRZK7Ql0b4=,tag:dbI1vPs6GQT2lhIO/C4GBQ==,type:str]
    pgp:
        - created_at: "2026-10-02T05:20:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8WjeZLD+fxwARAApMhomhUuaWmoSLVZuxI7X6ApmiiWc4ijzTBIJ0Fq1oGu
            Mx02jmT9X3Obx1vt9sBdSrhqyq3G3KGBsVlA4gAqqf2mY0iJTssatZyvQVgFPv8+
            DJmByQgTx53XiJVopH3rnDahqbS/yYTipKI5woJmQMqnR6tGnkEUmaoI+uFe666i
            Jcr8cyO/UU4gheKoBPghr/l2ny0FNN/l3TU1A/SC7EPbsKsAnCUS53imvl0OV8jk
            OhQF9pXcCO0hSQnefamwlF9lJ5nfCtdiafXowV7p3nzcyR9iEQbBzSzeQLT/Yfd9
            cWhj3zwFTL6KStJ/2XMLrjhRJ7DsP2mqkh+gAMcXnZbptnsE8Y1V0ye+8AhxAfS8
            i7oDbjIJ32wWSJ8vw/Mv0CB42bYvz30z4Pat32CTKDlcTKFVMy0V45UP/Igd7TO+
            V+vNx1buvBP2hP2xZEyNkffQTvpvdbrxPHY5BpKblyw4aH82UBXvWwexgSFcv2D0
            N64M0X9YskqIRsUhvyMUYACR940ykeCBHTMzhAScoxuYtDURQQu3OcjlPOXs+Tnk
            8OHJ3/Scwg9iu+qCMyHcLTLUcbyU5A9SwHIMrDRDINOdEGQxZBFkD915eWlqonBL
            GfTsTXoh9EMYxun1PbTXdVWc8YdcP/U4lpLfUanGc/QmkcKX11M55elkdwbmLmHS
            XAGu9EijTervK9zRd9A9Na+2zOSbbYMqllEUQQ48kLhNUsRkTn+V2QzMP6dOrfoC
            4iSjOQNg33cprx99Y8uv9ei7iIsBX61frmb+rpXYuRv2EGOIZRmpcmFG/Qf+
            =cfy8
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
