ingress:
    tls:
        - secretName: ENC[AES256_GCM,data:YzflKf8YE+Wl7cZtszadUQ==,iv:ahlJQk+e301Us3MBO3GQivfAqdlgMQ88VClzY4C1EzY=,tag:2Z8q2joB71sQKxcAYHqdJQ==,type:str]
          hosts:
            - ENC[AES256_GCM,data:NHGmYobZbP2/vPtUQQeP45RWTdej,iv:+5goARBKbjP/e+ejHpuCu/3WhuPwmlTH+uPl+eZGP2A=,tag:ZujVjthI5ca51ZaMcXi8FQ==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:504gOZTekGhhH+Xrml33SOR79D7y,iv:ZEQZD3Xf/bb6QuBB6kmbpoqsLp39Qxbvi+QtOkEWBRY=,tag:35iEasPftDOgw4xZgGbOjg==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:sQ==,iv:NuPICl3azKipMIZmVbUUZSoXZjhA0l6O1RjdXczoinY=,tag:OxxezaA1U1sbdtwZuvDTpA==,type:str]
              pathType: ENC[AES256_GCM,data:PQbEJrMX7mPsfRUOIkIdDIc1TPxSEw==,iv:LZbA+PfZC3FmQCGadfNshlT9vBPkPLNUfEtuMVZKRTw=,tag:JBbq+/bXLNlLRu/4xYYbsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-08T17:52:09Z"
    mac: ENC[AES256_GCM,data:UmT/Rq/8/6mFeyep1doeswSqyBsXFIjmRrwBjNax8xrcZDGxS30yz6L9hTR3A8frdR+/lRYFf55gf5YhmF8kYyT0Nek42NGCn6uELDQBemqhDVkxyts9TirlTSRZZd5oqnfonyCIPDcv+US9aH3YfrFBa98t4riAT6VSoFI2PKk=,iv:sWCxKrFyWU1itE2HfIbFC22RX3ffErekXW1hWaLvRGU=,tag:F4ZJScOlPu9UVf82G14Giw==,type:str]
    pgp:
        - created_at: "2025-07-08T17:52:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8WjeZLD+fxwAQ//Tmc2flV5qUcTnemnzCd0MWYGMiwwej9aInpzwy+gj2Pi
            TWtQlrm6stWeEpOWP9rynkRFcABbG248Gu+TlK64MZ6aA8WdOzhC527MDaNoGesl
            cZOTGrCJOqOy9kgMXkC8uqXJBkWQb2nWtd8gr8E+OC/WSvLUDyoRsOS32FQl0dJi
            UHCtKAzCPz4R92FGuhm8wRKMbe2COwEEFurn4NUOX+ioeSjlE8Vbl4KdUS/jhybF
            lpjWX+15zWjTEwoJZxFNwQCx62WYgTZa1djcqb543dlERIF7BSZfsNdj1fhRwUIJ
            QMlWomnduGc41uNRdizcUns80juj8/nXTjg/u2l0Tc9x6CsKuET+tesS7cyjxlfg
            7UVKI8qAw/udsMffHUcs/luCzXejlf+GpBGNEowWe9IR/nOyU5dV1xMDGoTl2bHJ
            wqw6f6LD8B0JU/rne2+7p95m4PGqAJCdmmZnQyRuybvmOUm+VJmjPiKMZ2XptFZe
            CIcRzv7JCkFOyF0QHMqFNdsaUUwZAJd7uMHEkF5cjNrBmpXPK0Qx1UT+gRPhh5Vn
            S4rcT4rAYFJqmsdQOUY9/QSa0m4F61m+8FK4+i1FfZ1SzKYMZ4wBG/p1vyinWP/Y
            LXaEJVuLWhpXP7VaM2BbGu9MKiKHvM0+4Rb88xb++ACLigz5Sa/ESdUN2pdf2nnS
            UQEmmP5PSr/4XRVSzKX+hnGeRClJQTCKJXAbEqfc+752N795e2hpgdpmwHuIGODx
            5SRyjr2XNz3n+nGSfyHST1Y/l4TV+mPM8Xt6SwgRT9VGEA==
            =JlwC
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ingress
    version: 3.9.2
