apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./volume.yaml
  - ./release.yaml
secretGenerator:
  - name: jellyfin-secret-values
    namespace: default
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
