apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 99999h
  timeout: 5m
  chart:
    spec:
      chart: jellyfin
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    ingress:
      enabled: false
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: nfs-csi
      media:
        enabled: true
        accessMode: ReadWriteMany
        size: 10Gi
        storageClass: nfs-csi
        existingClaim: pvc-jellyfin-media
    service:
      type: LoadBalancer
    livenessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 15
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 15
      failureThreshold: 6
      successThreshold: 1
  valuesFrom:
    - kind: Secret
      name: jellyfin-secret-values
