apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 99999h
  timeout: 5m
  chart:
    spec:
      chart: jellyfin
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: public
      annotations:
        external-dns.alpha.kubernetes.io/exclude: "true"
      tls:
        - secretName: fruitiex-org-tls
          hosts:
            - jellyfin.fruitiex.org
      hosts:
        - host: jellyfin.fruitiex.org
          paths:
            - path: /
              pathType: ImplementationSpecific
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: nfs-csi
      media:
        enabled: true
        accessMode: ReadWriteMany
        size: 10Gi
        storageClass: nfs-csi
        existingClaim: pvc-jellyfin-media
    service:
      type: LoadBalancer
    