apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferrotune
  namespace: default
spec:
  selector:
    matchLabels:
      app: ferrotune
  template:
    metadata:
      labels:
        app: ferrotune
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      volumes:
        - name: ferrotune-music
          persistentVolumeClaim:
            claimName: pvc-ferrotune-music
        - name: ferrotune-data
          persistentVolumeClaim:
            claimName: ferrotune-data
      containers:
        - name: ferrotune
          image: ghcr.io/fruitiex/ferrotune:main@sha256:e6d135315f40a06f955575936c95ee8c80a042c5dd3be2ff1e7b3881e2ee47ec
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: PORT
              value: "4040"
            - name: FERROTUNE_PORT
              value: "4040"
            - name: FERROTUNE_DB_MAX_CONNECTIONS
              value: "1"
            - name: FERROTUNE_DB_JOURNAL_MODE
              value: "delete"
            - name: FERROTUNE_DB_SYNCHRONOUS
              value: "normal"
            - name: FERROTUNE_DB_LOCKING_MODE
              value: "exclusive"
            - name: FERROTUNE_DB_BUSY_TIMEOUT
              value: "5"
          volumeMounts:
            - mountPath: /music
              name: ferrotune-music
              readOnly: true
            - mountPath: /data
              name: ferrotune-data
