apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferrotune
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: "ferrotune-env"
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: ferrotune
  template:
    metadata:
      labels:
        app: ferrotune
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      volumes:
        - name: ferrotune-music
          persistentVolumeClaim:
            claimName: pvc-ferrotune-music
        - name: ferrotune-data
          persistentVolumeClaim:
            claimName: ferrotune-data
      containers:
        - name: ferrotune
          image: ghcr.io/fruitiex/ferrotune:main@sha256:1edfec60f27471199c962ec9073b8859e8eb7235c76739e1aaa725a4b4b71b68
          envFrom:
            - secretRef:
                name: ferrotune-env
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: PORT
              value: "4040"
            - name: FERROTUNE_PORT
              value: "4040"
            - name: FERROTUNE_DB_MAX_CONNECTIONS
              value: "1"
            - name: FERROTUNE_DB_JOURNAL_MODE
              value: "delete"
            - name: FERROTUNE_DB_SYNCHRONOUS
              value: "normal"
            - name: FERROTUNE_DB_LOCKING_MODE
              value: "exclusive"
            #- name: FERROTUNE_DB_BUSY_TIMEOUT
              #value: "1"
          volumeMounts:
            - mountPath: /music
              name: ferrotune-music
            - mountPath: /data
              name: ferrotune-data
