apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: default
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:lIGLzl13l1TK2qV6GSrxa2/qliTif71LL2Je56Ki3WUKnwmzoOAkON0C0Qzm3s2jX+UcTVKbMZqFIXtl44FfwAwopkkHP+9ODOGhsJgjydWi+xV1R/v1fQwlqRFmNpxW9XtI69/nfHgEjtuO0oA08EyCR5YHKjG7O91YkYSoJSOigwD26Iv6Pg==,iv:vSd7ObQGoTakh2zGktYJHzcAUr2L9nlp7zsrNucTdR0=,tag:LciEA1E+0OGauPwAeKGBxQ==,type:str]
sops:
    lastmodified: "2025-12-09T10:03:14Z"
    mac: ENC[AES256_GCM,data:u2m0Rt0Sy1ze4lLv3yxW3aFuAo5cwaw/Rn+wGi3vhkkdhe2Go0cZsje7rflHwZA9cXebQAhuU+BAzLa0zwiiRCxpWzP+Tfha+PXU5FNO+hzAXKd9obnuciKhwwZ8Y9zXSMqMuqbOVzD6d+U0zBBYt/l3l2LIEP5vlxhtUBUY7aQ=,iv:GjD/fj4gbkHsNETbb/2fzkb+1rdFlEs8BhqAtVqSytE=,tag:Sz5UJNyENJlA0/BD0DoYiQ==,type:str]
    pgp:
        - created_at: "2025-12-09T10:03:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8WjeZLD+fxwAQ//RuhmyOutVc7OFE4UlF0GFlWGvm4uM3+R9+lTxvSct+eQ
            Fn6U4RlgdosEsQR7RdH3uG6WXhKdqoRdCIKF8xsZde2GWYTonOoPoYaaEjplHZtL
            w7WmAcDBJ7/uEut7k1p+p7v1wC+bZ0gkx5PMinXUkDqgRGkWJElADtMKiCcBQWDO
            c3OD/4bvpOigZB0xkYGIfe7JZ5IjhRka9Acldb5Rxy3FMa8pjoH6Yuad510sibVo
            duyJHRkBCkcqcFg0c3wSmXhUMdVYLZqjzJbeELO5vBzqoiyiA2ChV9m5kcBRHYyv
            46lCD8jkj87KeDZKG/i1JX857Vo/uARSMpfnYa8Cvj6P4GQC6Tuf/9CR4SdiKX2C
            K1nki31O/o4x18i6kabElwk5LYQlteZi8I2odcP9xfDgKhMwPe+JqSFNhR7zssZx
            8UpN+tzyHptWRY7m8AYouVxA1BTmWfXU2opFYwXfUelV79nQN6tFZWUAC5S1AI3L
            eS9TNpG8j0QQEYE1jx3pm5peq96iyJnEQhkaglnp+j1BNWq4z1/x0f/zfYJ8CvrN
            uLeDl6eUjBdpxqGZPdweJbvgYS42iuaAfvl5ikFFdnI1aXgK8wpic1oTDt+VJFA0
            ViUHZnMoGBdT3jg+F25IQjRmUiClrhdDa8ZwUy5+2mai7yi24g9mOB4CgDmMn3nS
            UQEJ34myn4mZxW/bq9SSrQi+du61RrzhJ0q21Gk8wVYnKiCNY88Nrv3cqrj/A+W3
            l8ZtQZOCrg/3VqaflkWJZBeP3Ll/KhiDHq5YEqKF3X/QSg==
            =mneL
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
