---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ferrotune-music
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nectarine.internal.fruitiex.org/volume3/music#ferrotune-music
    volumeAttributes:
      server: nectarine.internal.fruitiex.org
      share: /volume3
      subDir: music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ferrotune-music
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-ferrotune-music
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ferrotune-data
  namespace: default
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
