apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-public
  namespace: ingress-nginx-public
spec:
  interval: 5m
  timeout: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      ingressClassResource:
        name: public
      service:
        type: "LoadBalancer"
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.11.1
