apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-public
  namespace: ingress-nginx-public
spec:
  interval: 1h
  timeout: 3m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      electionID: ingress-controller-public
      ingressClassResource:
        name: public
        enabled: true
        default: false
        # controllerValue: "k8s.io/public-ingress-nginx"
      ingressClass: public
      ingressClassByName: true
      extraArgs:
        ingress-class: public
        controller-class: "k8s.io/public-ingress-nginx"
      service:
        type: "LoadBalancer"
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.11.1
