apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifx-mqtt
  namespace: default
spec:
  selector:
    matchLabels:
      app: lifx-mqtt
  template:
    metadata:
      labels:
        app: lifx-mqtt
    spec:
      volumes:
        - name: lifx-mqtt-config
          secret:
            secretName: lifx-mqtt-config

      containers:
        - name: lifx-mqtt
          image: ghcr.io/fruitiex/lifx-mqtt:0.2.0@sha256:4b27cfe1aa7e7b21add10707f7a3376c1067ae5924a44e04603fa34725670d4f
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: lifx-mqtt-config


