apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 99999h
  timeout: 3m
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.x
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system