apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: immich-git
    namespace: flux-system
spec:
    interval: 1h
    url: https://github.com/immich-app/immich-charts
    ref:
        #branch: main
        commit: 52aceac9bf0941cd00cbfa219d3ce7369a6de5f4
