apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: immich-git
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/immich-app/immich-charts
  ref:
    #branch: main
    commit: 4dff0ef9b1881e2a37d18144e38993b465e3e5cc
