apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cert-manager.yaml
  - ingress-nginx.yaml
  - kube-prometheus-stack.yaml
  - metallb.yaml
  - metrics-server.yaml
  - nfs-subdir-external-provisioner.yaml
  - reloader.yaml