---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adb-data
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adb-mqtt
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: "adb-mqtt-config"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adb-mqtt
  template:
    metadata:
      labels:
        app: adb-mqtt
    spec:
      volumes:
        - name: adb-mqtt-config
          secret:
            secretName: adb-mqtt-config
        - name: adb-data
          persistentVolumeClaim:
            claimName: adb-data

      containers:
        - name: adb-mqtt
          image: ghcr.io/fruitiex/adb-mqtt:0.1.1@sha256:67649eb88b31ecb6b25337260800333467dac283a99d74b30232dd0867e3da35
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: adb-mqtt-config
            - mountPath: /root/.android
              name: adb-data
