apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: nectarine
    namespace: ingress-proxy
    annotations:
        external-dns.alpha.kubernetes.io/exclude: "true"
spec:
    parentRefs:
        - name: public
          namespace: envoy-gateway-system
          sectionName: https
    hostnames:
        - ENC[AES256_GCM,data:TQp7CGmsO3GmsaajV0YgkLXBjcyXEg==,iv:p0gZK81L4y+HmZ+y1FPdiS/GX5XEWe6kk/rk+opEN+Y=,tag:KQTIM5XsFcGSkqzN3jVmyQ==,type:str]
    rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - group: gateway.envoyproxy.io
              kind: Backend
              name: nectarine-5000
sops:
    encrypted_regex: ^(hosts?|hostnames?)$
    lastmodified: "2026-08-29T13:22:04Z"
    mac: ENC[AES256_GCM,data:YTeRiqIH7e2F+bCVw57tNcKIk/WhT7RDiv+rQq2WQjPh1mvW32D4tQQibrr2Hzlz1EAVWzqy+zDn4IGhn6+giM14TszqvDiX+VxzDpWc4/gkwFt5EDPNUSDlus8YwXH8LmjFrjrjDu13TzFPVoT5uiy/mJsMG/+3AohK5B12E2U=,iv:HPFt2ZqBwr52tFh7c5kXsgY1fYyg3wnoAK0anwRyshQ=,tag:vpKNq3iBPm8HwPlhsHWxZA==,type:str]
    pgp:
        - created_at: "2026-08-29T13:22:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8WjeZLD+fxwAQ/+KwQMsloOnJckFLnLtRZu7t/gHXMfPKfLD4XhatZTL7ki
            60ukeE8tyDW6fM+b4cR6SbZB2B88yh1+qavwbvMbXHxF7VMzJ8eEyx0YQe2D733L
            0PiwtA4fY5JubDeG+UzIyiZOxJGyfdp0mzWooRbvf8/M/ljqEJck8vhzehNIxu77
            UGgz40ipfcZXkXQ8eD5vPC1C9eK3943X9jiW+U/CexsMJYp30/nr8wY/5/6omUlG
            9duuW3nMNROuIVCUpK2wMIyou5IBXsF1RvHi9ZjOCELLY2iGTmalLjEkk3qHszRQ
            c6tVMaUOVZsclurczUip8CR/OP10vG3kaWUvdFtoZZGTKEEbnJnbtIps26vCVMok
            Z4daCx0Ho/6TshWSqIq2QeatUS9xyH93frHvbrrfTy/UMdvdQiK1svJ8noKxCTKX
            aNYvFkwrz4Gp8lzytPmHJH1L8UPlDPnnMNpGm6BeC4PKVJQaKGCy+nvQ2Si7VQUd
            7Bl6PkaRY1YZTvKdVsRQayqTSLFeuFyTCJmbO0EL7M6rzBLVJiA+ET0kLWQQ8AvU
            08Z89T7j9qnzlOu3B/SwrejhaPCwsJuqr+Pw2oM/9vL9ILlO9JAfe5P/+PxHWeAG
            PKOl8+fZQ2QMoz+IQe0ZaAmpuGtB7z7w8oJ6abb3v0tRl5L0190aorLbtWjzMNrS
            XgEjYhpGEvg1pGEq/YhBpyHL1rDJhL/fmQ5eXCEuzn9KPr7xr0ZdHF+4HrrZ2AAn
            jgcxTfFC9cNBcPX0AvOXciNFAr4PwBcAszEA2bed6Hl7OTqJlmiDF9AMcB1hSlw=
            =cMGA
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    version: 3.13.3
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: drive-primary
    namespace: ingress-proxy
    annotations:
        external-dns.alpha.kubernetes.io/exclude: "true"
spec:
    parentRefs:
        - name: public
          namespace: envoy-gateway-system
          sectionName: https
    hostnames:
        - ENC[AES256_GCM,data:xiJwGW8ufz7QNfiKWQns+u5C,iv:ejCdU8C/q0hI8b9fKE/LFsXpfbPtzP9BtHBx933i86E=,tag:BiNO0aRrZe1N0fxBuOKO7Q==,type:str]
    rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - group: gateway.envoyproxy.io
              kind: Backend
              name: nectarine-10002
sops:
    encrypted_regex: ^(hosts?|hostnames?)$
    lastmodified: "2026-08-29T13:22:04Z"
    mac: ENC[AES256_GCM,data:YTeRiqIH7e2F+bCVw57tNcKIk/WhT7RDiv+rQq2WQjPh1mvW32D4tQQibrr2Hzlz1EAVWzqy+zDn4IGhn6+giM14TszqvDiX+VxzDpWc4/gkwFt5EDPNUSDlus8YwXH8LmjFrjrjDu13TzFPVoT5uiy/mJsMG/+3AohK5B12E2U=,iv:HPFt2ZqBwr52tFh7c5kXsgY1fYyg3wnoAK0anwRyshQ=,tag:vpKNq3iBPm8HwPlhsHWxZA==,type:str]
    pgp:
        - created_at: "2026-08-29T13:22:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8WjeZLD+fxwAQ/+KwQMsloOnJckFLnLtRZu7t/gHXMfPKfLD4XhatZTL7ki
            60ukeE8tyDW6fM+b4cR6SbZB2B88yh1+qavwbvMbXHxF7VMzJ8eEyx0YQe2D733L
            0PiwtA4fY5JubDeG+UzIyiZOxJGyfdp0mzWooRbvf8/M/ljqEJck8vhzehNIxu77
            UGgz40ipfcZXkXQ8eD5vPC1C9eK3943X9jiW+U/CexsMJYp30/nr8wY/5/6omUlG
            9duuW3nMNROuIVCUpK2wMIyou5IBXsF1RvHi9ZjOCELLY2iGTmalLjEkk3qHszRQ
            c6tVMaUOVZsclurczUip8CR/OP10vG3kaWUvdFtoZZGTKEEbnJnbtIps26vCVMok
            Z4daCx0Ho/6TshWSqIq2QeatUS9xyH93frHvbrrfTy/UMdvdQiK1svJ8noKxCTKX
            aNYvFkwrz4Gp8lzytPmHJH1L8UPlDPnnMNpGm6BeC4PKVJQaKGCy+nvQ2Si7VQUd
            7Bl6PkaRY1YZTvKdVsRQayqTSLFeuFyTCJmbO0EL7M6rzBLVJiA+ET0kLWQQ8AvU
            08Z89T7j9qnzlOu3B/SwrejhaPCwsJuqr+Pw2oM/9vL9ILlO9JAfe5P/+PxHWeAG
            PKOl8+fZQ2QMoz+IQe0ZaAmpuGtB7z7w8oJ6abb3v0tRl5L0190aorLbtWjzMNrS
            XgEjYhpGEvg1pGEq/YhBpyHL1rDJhL/fmQ5eXCEuzn9KPr7xr0ZdHF+4HrrZ2AAn
            jgcxTfFC9cNBcPX0AvOXciNFAr4PwBcAszEA2bed6Hl7OTqJlmiDF9AMcB1hSlw=
            =cMGA
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    version: 3.13.3
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: photos-primary
    namespace: ingress-proxy
    annotations:
        external-dns.alpha.kubernetes.io/exclude: "true"
spec:
    parentRefs:
        - name: public
          namespace: envoy-gateway-system
          sectionName: https
    hostnames:
        - ENC[AES256_GCM,data:eH0bIJ/4/ZPrXbVv+2uJll0hfw==,iv:JUKljRrGW5TO+nr93V1WF4KeOW0lYsXeWJ1lls1CYgI=,tag:qB4kMUAgyPcB523sieOpyw==,type:str]
    rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - group: gateway.envoyproxy.io
              kind: Backend
              name: nectarine-5081
sops:
    encrypted_regex: ^(hosts?|hostnames?)$
    lastmodified: "2026-08-29T13:22:04Z"
    mac: ENC[AES256_GCM,data:YTeRiqIH7e2F+bCVw57tNcKIk/WhT7RDiv+rQq2WQjPh1mvW32D4tQQibrr2Hzlz1EAVWzqy+zDn4IGhn6+giM14TszqvDiX+VxzDpWc4/gkwFt5EDPNUSDlus8YwXH8LmjFrjrjDu13TzFPVoT5uiy/mJsMG/+3AohK5B12E2U=,iv:HPFt2ZqBwr52tFh7c5kXsgY1fYyg3wnoAK0anwRyshQ=,tag:vpKNq3iBPm8HwPlhsHWxZA==,type:str]
    pgp:
        - created_at: "2026-08-29T13:22:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8WjeZLD+fxwAQ/+KwQMsloOnJckFLnLtRZu7t/gHXMfPKfLD4XhatZTL7ki
            60ukeE8tyDW6fM+b4cR6SbZB2B88yh1+qavwbvMbXHxF7VMzJ8eEyx0YQe2D733L
            0PiwtA4fY5JubDeG+UzIyiZOxJGyfdp0mzWooRbvf8/M/ljqEJck8vhzehNIxu77
            UGgz40ipfcZXkXQ8eD5vPC1C9eK3943X9jiW+U/CexsMJYp30/nr8wY/5/6omUlG
            9duuW3nMNROuIVCUpK2wMIyou5IBXsF1RvHi9ZjOCELLY2iGTmalLjEkk3qHszRQ
            c6tVMaUOVZsclurczUip8CR/OP10vG3kaWUvdFtoZZGTKEEbnJnbtIps26vCVMok
            Z4daCx0Ho/6TshWSqIq2QeatUS9xyH93frHvbrrfTy/UMdvdQiK1svJ8noKxCTKX
            aNYvFkwrz4Gp8lzytPmHJH1L8UPlDPnnMNpGm6BeC4PKVJQaKGCy+nvQ2Si7VQUd
            7Bl6PkaRY1YZTvKdVsRQayqTSLFeuFyTCJmbO0EL7M6rzBLVJiA+ET0kLWQQ8AvU
            08Z89T7j9qnzlOu3B/SwrejhaPCwsJuqr+Pw2oM/9vL9ILlO9JAfe5P/+PxHWeAG
            PKOl8+fZQ2QMoz+IQe0ZaAmpuGtB7z7w8oJ6abb3v0tRl5L0190aorLbtWjzMNrS
            XgEjYhpGEvg1pGEq/YhBpyHL1rDJhL/fmQ5eXCEuzn9KPr7xr0ZdHF+4HrrZ2AAn
            jgcxTfFC9cNBcPX0AvOXciNFAr4PwBcAszEA2bed6Hl7OTqJlmiDF9AMcB1hSlw=
            =cMGA
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    version: 3.13.3
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: drive-secondary
    namespace: ingress-proxy
    annotations:
        external-dns.alpha.kubernetes.io/exclude: "true"
spec:
    parentRefs:
        - name: public
          namespace: envoy-gateway-system
          sectionName: https
    hostnames:
        - ENC[AES256_GCM,data:WR1HXwsc48rylBzk0PW3WmI=,iv:PeZI2pokglx14g7EYq5n+wQGPD1JK/K2r6O2VGeq1Zw=,tag:fsoO9INvrWvj0XZj2uSC9A==,type:str]
    rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - group: gateway.envoyproxy.io
              kind: Backend
              name: nectarine-10002
sops:
    encrypted_regex: ^(hosts?|hostnames?)$
    lastmodified: "2026-08-29T13:22:04Z"
    mac: ENC[AES256_GCM,data:YTeRiqIH7e2F+bCVw57tNcKIk/WhT7RDiv+rQq2WQjPh1mvW32D4tQQibrr2Hzlz1EAVWzqy+zDn4IGhn6+giM14TszqvDiX+VxzDpWc4/gkwFt5EDPNUSDlus8YwXH8LmjFrjrjDu13TzFPVoT5uiy/mJsMG/+3AohK5B12E2U=,iv:HPFt2ZqBwr52tFh7c5kXsgY1fYyg3wnoAK0anwRyshQ=,tag:vpKNq3iBPm8HwPlhsHWxZA==,type:str]
    pgp:
        - created_at: "2026-08-29T13:22:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8WjeZLD+fxwAQ/+KwQMsloOnJckFLnLtRZu7t/gHXMfPKfLD4XhatZTL7ki
            60ukeE8tyDW6fM+b4cR6SbZB2B88yh1+qavwbvMbXHxF7VMzJ8eEyx0YQe2D733L
            0PiwtA4fY5JubDeG+UzIyiZOxJGyfdp0mzWooRbvf8/M/ljqEJck8vhzehNIxu77
            UGgz40ipfcZXkXQ8eD5vPC1C9eK3943X9jiW+U/CexsMJYp30/nr8wY/5/6omUlG
            9duuW3nMNROuIVCUpK2wMIyou5IBXsF1RvHi9ZjOCELLY2iGTmalLjEkk3qHszRQ
            c6tVMaUOVZsclurczUip8CR/OP10vG3kaWUvdFtoZZGTKEEbnJnbtIps26vCVMok
            Z4daCx0Ho/6TshWSqIq2QeatUS9xyH93frHvbrrfTy/UMdvdQiK1svJ8noKxCTKX
            aNYvFkwrz4Gp8lzytPmHJH1L8UPlDPnnMNpGm6BeC4PKVJQaKGCy+nvQ2Si7VQUd
            7Bl6PkaRY1YZTvKdVsRQayqTSLFeuFyTCJmbO0EL7M6rzBLVJiA+ET0kLWQQ8AvU
            08Z89T7j9qnzlOu3B/SwrejhaPCwsJuqr+Pw2oM/9vL9ILlO9JAfe5P/+PxHWeAG
            PKOl8+fZQ2QMoz+IQe0ZaAmpuGtB7z7w8oJ6abb3v0tRl5L0190aorLbtWjzMNrS
            XgEjYhpGEvg1pGEq/YhBpyHL1rDJhL/fmQ5eXCEuzn9KPr7xr0ZdHF+4HrrZ2AAn
            jgcxTfFC9cNBcPX0AvOXciNFAr4PwBcAszEA2bed6Hl7OTqJlmiDF9AMcB1hSlw=
            =cMGA
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    version: 3.13.3
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: photos-secondary
    namespace: ingress-proxy
    annotations:
        external-dns.alpha.kubernetes.io/exclude: "true"
spec:
    parentRefs:
        - name: public
          namespace: envoy-gateway-system
          sectionName: https
    hostnames:
        - ENC[AES256_GCM,data:ZHjvtwNxoYhMjV3CMl1Qbsnv,iv:nZggSQrkaAg4JFJn5vaKkscw/VKy7iaVqhPi9Y7+uV4=,tag:haRb3/0Lm1yyziihIJV3yw==,type:str]
    rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - group: gateway.envoyproxy.io
              kind: Backend
              name: nectarine-5081
sops:
    encrypted_regex: ^(hosts?|hostnames?)$
    lastmodified: "2026-08-29T13:22:04Z"
    mac: ENC[AES256_GCM,data:YTeRiqIH7e2F+bCVw57tNcKIk/WhT7RDiv+rQq2WQjPh1mvW32D4tQQibrr2Hzlz1EAVWzqy+zDn4IGhn6+giM14TszqvDiX+VxzDpWc4/gkwFt5EDPNUSDlus8YwXH8LmjFrjrjDu13TzFPVoT5uiy/mJsMG/+3AohK5B12E2U=,iv:HPFt2ZqBwr52tFh7c5kXsgY1fYyg3wnoAK0anwRyshQ=,tag:vpKNq3iBPm8HwPlhsHWxZA==,type:str]
    pgp:
        - created_at: "2026-08-29T13:22:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8WjeZLD+fxwAQ/+KwQMsloOnJckFLnLtRZu7t/gHXMfPKfLD4XhatZTL7ki
            60ukeE8tyDW6fM+b4cR6SbZB2B88yh1+qavwbvMbXHxF7VMzJ8eEyx0YQe2D733L
            0PiwtA4fY5JubDeG+UzIyiZOxJGyfdp0mzWooRbvf8/M/ljqEJck8vhzehNIxu77
            UGgz40ipfcZXkXQ8eD5vPC1C9eK3943X9jiW+U/CexsMJYp30/nr8wY/5/6omUlG
            9duuW3nMNROuIVCUpK2wMIyou5IBXsF1RvHi9ZjOCELLY2iGTmalLjEkk3qHszRQ
            c6tVMaUOVZsclurczUip8CR/OP10vG3kaWUvdFtoZZGTKEEbnJnbtIps26vCVMok
            Z4daCx0Ho/6TshWSqIq2QeatUS9xyH93frHvbrrfTy/UMdvdQiK1svJ8noKxCTKX
            aNYvFkwrz4Gp8lzytPmHJH1L8UPlDPnnMNpGm6BeC4PKVJQaKGCy+nvQ2Si7VQUd
            7Bl6PkaRY1YZTvKdVsRQayqTSLFeuFyTCJmbO0EL7M6rzBLVJiA+ET0kLWQQ8AvU
            08Z89T7j9qnzlOu3B/SwrejhaPCwsJuqr+Pw2oM/9vL9ILlO9JAfe5P/+PxHWeAG
            PKOl8+fZQ2QMoz+IQe0ZaAmpuGtB7z7w8oJ6abb3v0tRl5L0190aorLbtWjzMNrS
            XgEjYhpGEvg1pGEq/YhBpyHL1rDJhL/fmQ5eXCEuzn9KPr7xr0ZdHF+4HrrZ2AAn
            jgcxTfFC9cNBcPX0AvOXciNFAr4PwBcAszEA2bed6Hl7OTqJlmiDF9AMcB1hSlw=
            =cMGA
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    version: 3.13.3
