apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nectarine-lovegren-fi
    namespace: ingress-proxy
    annotations:
        cert-manager.io/cluster-issuer: ${LETSENCRYPT_CLUSTER_ISSUER}
        external-dns.alpha.kubernetes.io/exclude: "true"
spec:
    ingressClassName: public
    tls:
        - secretName: nectarine-tls
    rules:
        - host: ENC[AES256_GCM,data:xv6IrZkpPgdVISZSHBlDHEc=,iv:hiUDtrQQza7UpvpDUPAo8t6rbovOTulkYYF4jhB/m+8=,tag:YK5YYOSQcFK1m740hqUk+w==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: nectarine
                        port:
                            number: 10002
        - host: ENC[AES256_GCM,data:rpmCFAHWj01YMsqRHnJe9GQi,iv:RauaHCpuzq1VBwpF7ZeT5AQTZ/5xdTlBaVMPZxp1NbY=,tag:MphsZnaOpEYDrY4i4EgKOg==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: nectarine
                        port:
                            number: 5081
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-27T14:57:20Z"
    mac: ENC[AES256_GCM,data:HmK/FzMyRt2FHt1i2QOgAKSw+kx8Tp5dmecNjyPkT/KartfUfM3Ov6XGaXKiiRaVbWuzP0EzU6EOFTvXmbCrUt9jBFTvKs7Wcqb9KPF/qEvjHhZvIp8IszfIOkuG/SU2cCc9RxpMmCN8AZpJHrI+W8db6Wx8p20TwsyT+jZsSJk=,iv:B+KSXk9hWaaobJWQyP2kUcoKGA26Y0yp+tL4majxphw=,tag:/MzFZZi9x/supePW6GTuwA==,type:str]
    pgp:
        - created_at: "2023-04-10T17:59:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8WjeZLD+fxwAQ//Y0MfVpk9G0PvpfLWMevIARlNbInfcRxDswfvNHK6Wjc7
            mudjGPdluetccIQVCbcSHskdoqNUxGXaFEsWq+xrmVyVtt5aVQ9GHq48G8StM4iu
            x04xPdcdUjTy9m/kzzLbEdnmAxJ8JXBG72utod5sGncYDTHOtvHAeBilAst2sTnz
            Cv1Pyf9bJSMUCgU0h9ajVwmOZBcZGkGEbgq66svJLArAxCWAW2H/he7HRAJn+asG
            JyJaxplH2jyC8sB7xZ2Pcua8fpfeYjvL2m9DBGHmhIjMZFaUmQ7npYkGlbMZAqPg
            E5W7n2N+DoTP6H81jcbjuzKAcaGqxVJEdfeOz0CSRHOR8BSfDnDpbReOwmJlgq1V
            YgSoUZqHCFu+Mz07KJuIyDneizQh3gLG6IICwQaLoMh0nyBac7iVyQsuokQzq+p6
            xTAF/uQ4fP90bCig5aWi97rRFCf1eXQ68s+fh0RHqxcTCGNGm3nekc8ofkeOVynh
            /Cf4H4enq1HvqYA9Hko/t/MpcCC4l3YDcTE/oczoefQRMVXCw7sWG+aREmhB0uL8
            CcscylJZvUPrgX1DEZ9RYfaxJxzs3GYaMzPdG/bHEP452kI+5geyh9yRI2S/+LB8
            q9jWm82JuxMBJncz4m5SRBvinXnZHuotcoECCF2Ga6Wov+6lA/nM8R+HtF+QSr3S
            UQE5d5DDWiQGK7bIBcTwO80le+ojyUpbXCm4HTioZtjX4pP8eFNFJpDqsJu+A2Cu
            H1ye2GX0h7exzQkdMXEumjFoeJpyWLJ0n6fNef1PVTG2Eg==
            =ladq
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(hosts?)$
    version: 3.8.0
