apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nectarine-lovegren-fi
    namespace: ingress-proxy
    annotations:
        cert-manager.io/cluster-issuer: ${LETSENCRYPT_CLUSTER_ISSUER}
        external-dns.alpha.kubernetes.io/exclude: "true"
spec:
    ingressClassName: public
    tls:
        - hosts:
            - ENC[AES256_GCM,data:+OL6TXENhHHjPw5UU9oal94=,iv:G5M5aTKXhQnZEK3qG4c8UhCqpcMQWthF6SfTKhLdqhE=,tag:+7oft11Y94JEJJis3YBVYg==,type:str]
            - ENC[AES256_GCM,data:eYgNcphANZyRjQVKeu6i6NwS,iv:ly35YD769N0jT8bFBu+41Z/bD+VUiA19VudHZPLE9L4=,tag:owe2WFHm/TGpSGeRkmNBiw==,type:str]
          secretName: nectarine-tls
    rules:
        - host: ENC[AES256_GCM,data:xv6IrZkpPgdVISZSHBlDHEc=,iv:hiUDtrQQza7UpvpDUPAo8t6rbovOTulkYYF4jhB/m+8=,tag:YK5YYOSQcFK1m740hqUk+w==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: nectarine
                        port:
                            number: 10002
        - host: ENC[AES256_GCM,data:rpmCFAHWj01YMsqRHnJe9GQi,iv:RauaHCpuzq1VBwpF7ZeT5AQTZ/5xdTlBaVMPZxp1NbY=,tag:MphsZnaOpEYDrY4i4EgKOg==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: nectarine
                        port:
                            number: 5081
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-20T18:08:48Z"
    mac: ENC[AES256_GCM,data:GjdLVxoa77PQyhI9ND/Abrfd7TYOhOmHrm1G1wWfNAsLb/4rwy8w2mE8PmFqnxllpFsm9ZGFZK+UPFy+HvcClVlV7pAnPAc1ODFpI4ZpCL2FjYzdk5z006sP5P2M1E96ZnImlsIE5E+8wDyn3E1vZi6lSTwdatsErrn8xJb7Nhs=,iv:YDEKJB8dHue4TrCZ+dT3tMyKAptdUb3ItoEXEgZnXxM=,tag:z4eH2DZxIIEyzRzgt015Yw==,type:str]
    pgp:
        - created_at: "2023-04-10T17:59:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8WjeZLD+fxwAQ//Y0MfVpk9G0PvpfLWMevIARlNbInfcRxDswfvNHK6Wjc7
            mudjGPdluetccIQVCbcSHskdoqNUxGXaFEsWq+xrmVyVtt5aVQ9GHq48G8StM4iu
            x04xPdcdUjTy9m/kzzLbEdnmAxJ8JXBG72utod5sGncYDTHOtvHAeBilAst2sTnz
            Cv1Pyf9bJSMUCgU0h9ajVwmOZBcZGkGEbgq66svJLArAxCWAW2H/he7HRAJn+asG
            JyJaxplH2jyC8sB7xZ2Pcua8fpfeYjvL2m9DBGHmhIjMZFaUmQ7npYkGlbMZAqPg
            E5W7n2N+DoTP6H81jcbjuzKAcaGqxVJEdfeOz0CSRHOR8BSfDnDpbReOwmJlgq1V
            YgSoUZqHCFu+Mz07KJuIyDneizQh3gLG6IICwQaLoMh0nyBac7iVyQsuokQzq+p6
            xTAF/uQ4fP90bCig5aWi97rRFCf1eXQ68s+fh0RHqxcTCGNGm3nekc8ofkeOVynh
            /Cf4H4enq1HvqYA9Hko/t/MpcCC4l3YDcTE/oczoefQRMVXCw7sWG+aREmhB0uL8
            CcscylJZvUPrgX1DEZ9RYfaxJxzs3GYaMzPdG/bHEP452kI+5geyh9yRI2S/+LB8
            q9jWm82JuxMBJncz4m5SRBvinXnZHuotcoECCF2Ga6Wov+6lA/nM8R+HtF+QSr3S
            UQE5d5DDWiQGK7bIBcTwO80le+ojyUpbXCm4HTioZtjX4pP8eFNFJpDqsJu+A2Cu
            H1ye2GX0h7exzQkdMXEumjFoeJpyWLJ0n6fNef1PVTG2Eg==
            =ladq
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(hosts?)$
    version: 3.7.3
