---
apiVersion: v1
kind: Service
metadata:
  name: nectarine
  namespace: ingress-proxy
spec:
  type: ExternalName
  externalName: nectarine
---
apiVersion: v1
kind: Service
metadata:
  name: satsuma
  namespace: ingress-proxy
spec:
  type: ExternalName
  externalName: satsuma