apiVersion: apps/v1
kind: Deployment
metadata:
  name: homectl-server
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: "homectl-server-settings"
spec:
  selector:
    matchLabels:
      app: homectl-server
  template:
    metadata:
      labels:
        app: homectl-server
    spec:
      volumes:
        - name: homectl-server-settings
          secret:
            secretName: homectl-server-settings

      containers:
        - name: homectl-server
          image: ghcr.io/fruitiex/homectl-server:main@sha256:f2d314e21f515edbec378682e735f6bd4a87f29637171bc9563091b87bf44077
          envFrom:
            - secretRef:
                name: homectl-server-env
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: RUST_LOG
              value: "homectl_server=info"
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: homectl-server-settings

      initContainers:
        - name: wait-for-mqtt-broker
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z mqtt 1883; do echo waiting for mqtt broker; sleep 1; done",
            ]
