apiVersion: apps/v1
kind: Deployment
metadata:
  name: homectl-server
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: "homectl-server-settings"
spec:
  selector:
    matchLabels:
      app: homectl-server
  template:
    metadata:
      labels:
        app: homectl-server
    spec:
      volumes:
        - name: homectl-server-settings
          secret:
            secretName: homectl-server-settings

      containers:
        - name: homectl-server
          image: ghcr.io/fruitiex/homectl-server:latest
          envFrom:
            - secretRef:
                name: homectl-server-env
          env:
            - name: TZ
              value: Europe/Helsinki
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: homectl-server-settings
