apiVersion: v1
kind: Service
metadata:
  name: homectl-server
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: homectl-server
  ports:
  - name: homectl-server
    protocol: TCP
    port: 45289
    targetPort: 45289