apiVersion: v1
kind: Secret
metadata:
    name: radiator-secrets
    namespace: default
type: Opaque
stringData:
    MANAGEMENT_PASSWORD: ENC[AES256_GCM,data:JQsXqfbNYlmvM+Jytp8QclKt1JQhY16T6mleGeLYaos=,iv:d8ywD8W4dhOHm+kKwC339364p5zvyJmmX8EAD8BsBAw=,tag:FW4DcHy+8Y0xE/xsIZI1YQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:b0VntcVfyHKXw3+sOGome5ns23IvJwDH+XAIuqX+OpE=,iv:pWU5EsWx9H+MAiGbd25LuePdsLXN1PfVPu+Fjpgpd0o=,tag:xJCnZ7IKgYuajHuZv7HQTQ==,type:str]
    RADIUS_SHARED_SECRET: ENC[AES256_GCM,data:uiqtNlTgdxwdm6H4epqS4BITQ7f8iR4DBHuobWz8y/s=,iv:F+3Rf+6C9fJJYUTxKtFHkDMiXYsEAvsxJVMvGnOaZ6w=,tag:Lgxudxz/QZx0CsqrEmuP4g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:lZRMSSTxDRwzUhI/c/0phw==,iv:UJeJCcsQAaaoONkiwZkanuG8goGSfje5fMwGqFa2Bjw=,tag:4RCHqNRsuqSu9GdAYb0A5g==,type:str]
    MANAGEMENT_USERS_JSON: ENC[AES256_GCM,data:/liC2+9bBbGOEjkyLvUplL47IsFZruejIyHe6Pq7ufEHFzvVNmbvas3dopnVf3KSPmFgZP3RMooXqCOrf+gngEFBT6z/oDhYeWQg5NEOPEmfRERCfZHI8B2+ujXGfRPNoUijdg9wWQSjEVZFueDLLkzE,iv:OkChqpP6WF0rVxnBZhpptaD+ITYphCJZo0t0g+05XV0=,tag:TFopl0fnjHt9yq+mb9IBYQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T12:05:47Z"
    mac: ENC[AES256_GCM,data:8GBIuHXcqmTAAIPmy+SCEoO3ripEncgUIG/l6rqz9JVimchDRJj5lQ/fZZfzKet7bpCztQR40YhZMm1HJb0GnNxb+SmE43+Ho6kSChoFpaFdz75mHcXdQRFGpLi5KE7n4c99BlJToLHYOQX0dJ3JWLnGPQHUmVLum3L9e+0rzvc=,iv:ega+Vv2cprE2nUUerpQjeTL+orVQnXkE7rAAfHRGomw=,tag:KWG3QVj/2EAZ51vNKpgVdg==,type:str]
    pgp:
        - created_at: "2026-08-25T11:01:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8WjeZLD+fxwARAAvdITyhmkS2Cd8S30lboAOqtzX437hOCCZ2uLKmjnPDQZ
            OLc6Y3YZVePO9pxIH/rSJYeD8Fiz+w+CFD9gOmOBdkrlGXfA+PWVJK3j4MJcPx89
            XBamBY2xSymztv71AGVymuS43mAYelPDiyXsyExSyVKuo8xSlwWFryqpWl/lAWOp
            quCLCtz4BF3MhXEgFOzN3ERWXGfJ6cMdnTylJHTpBalm2JRGXTAchkdNEh1kNXG8
            WaGwOygIAIJu678yy44CYA0/5HWaffAJpfp7SG6w7zxcCycx3csFmaoFskptVpyz
            ibsSkSJLneI4WtnX2LVUQV4y6RBVHOVRzoLO32REgeqUcC3L4MqMQTZ1XMBPie4I
            Dft/RUCuTdivdL+yyztCEaYiTAun2fPvdj0fIqvzac0xRQNJELzxsJoOA8GcqH+S
            O+P5u1CXZubsKzBNK5aKD1ia378KA5Huo1SLFthDC5LeQHfg5y7JdfBV8X8WS7Nt
            nuM9ZYtbeOOg9FrbP1uQHEM/AmFMejDwZLyS/aIKwB9PpZwzXsoFeks8Tzzy7Rnf
            NVswmu0M3ufOParJVahPHBlJxH454E9WVR7MWIjIV08h76EYq4lPILsuB0beHamq
            VCMc0+MCnfhm20yOARg5lVuN1rK+eG1t2k8uRuEISLdixiuYIsKWUuENM1UTCUfS
            XAGF4tb9eJoQ2tBuovW5NAKM+H7PjWS+wI+RfXG78GjHS5D9c6xIA3WAG7sk/cBY
            X+/SeBzKMkBF8R540um2BSxo2OBukUPf/dOoY8Ss6nzPUgPXcoyYOHX8+Rxc
            =llf1
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    version: 3.13.3
