apiVersion: v1
kind: Service
metadata:
  name: varnish-svc
  namespace: default
spec:
  ports:
  - name: "http"
    port: 80
  selector:
    app: varnish-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish-proxy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: varnish-proxy
  template:
    metadata:
      name: varnish-proxy
      labels:
        app: varnish-proxy
    spec:
      volumes:
        - name: varnish-config
          configMap:
            name: varnish-vcl
      containers:
      - name: varnish
        image: varnish:alpine
        imagePullPolicy: Always
        env:
        - name: VARNISH_HTTP_PORT
          value: "8080"
        - name: VCL_CONFIG
          value: /etc/varnish/configmap/default.vcl
        volumeMounts:
          - name: varnish-config
            mountPath: /etc/varnish/configmap
        ports:
        - containerPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: varnish-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  # - host: fruitiex.example.com
  - http:
      paths:
      - path: /weather
        pathType: Prefix
        backend:
          service:
            name: varnish-svc
            port:
              number: 8080