apiVersion: apps/v1
kind: Deployment
metadata:
  name: nordpool-mqtt
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: "nordpool-mqtt-config"
spec:
  selector:
    matchLabels:
      app: nordpool-mqtt
  template:
    metadata:
      labels:
        app: nordpool-mqtt
    spec:
      volumes:
        - name: nordpool-mqtt-config
          secret:
            secretName: nordpool-mqtt-config

      containers:
        - name: nordpool-mqtt
          image: ghcr.io/fruitiex/nordpool-mqtt:main@sha256:af6e1fa21c85711df6a7ba100539987bbb0e2e274b6f178d539c345c12719234
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: nordpool-mqtt-config

      initContainers:
        - name: wait-for-mqtt-broker
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z mqtt 1883; do echo waiting for mqtt broker; sleep 1; done",
            ]
