apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: homectl-next-settings
type: Opaque
stringData:
    .env: ENC[AES256_GCM,data:wwIEo/PO7bLgapQhxaDXS/YDS9JeWb0uChGDokbwn8OF7oBPns7Q3R8lDE9w9Dcb0W1ntSI23znf9HJeUW/8zOJjn7offDHGuzz7mZ1heA+wo2u1+vwfbrF85uxX10FZ4ekB+STBV/lFojDUPGb/d6BMlxQc/RjsI9//Yae73LDhIAkEf7eokstTSzusjDulqL/elGlIOw7GqV+zUBxicQhVqRN0eBveYaQKVAuqUcOX6s8CaBp3N93xCKVnUfl1pDlqN4/LcftNgUrms5iXx5OnW35vKEr3yUnsR/IalxBqAc66i71cy2TQ3IcTKa1RxH0dVA+GUhw/uVgGmyjV48seoib8B1L1h6aZcVfj9G8HNlpA1msa6kFZPaaB2Rrut19BE+kXaGVvtdw5vK8dXRBe5RWwbi8RePOlohJFrKUjHijCc3aRYIykrs0pe8VTg38j+bt40xvPJhTghdnAy+BdNtO5WsTPcmQzfkLr5WylGt7cUJqQ7C2SeiaTwr+h4pjCAp9BrUzPseYYFlYd1TukCwkfOTYAxg5QZjG/OQS54lnnfuHevNmKlxiI+P1TAOQjM5WcwqgUWTFhksrCYTbJoE5eTvgiIAQijhMJ6XR77tisv7IjP6dOmqsd5yRsHR/qgVl4Af20aI/NEkTuw/2yDVZlDUNsD9en0qACvm+d8lfNiYFY8Qd+k6dLoWctwgJMQ1bmRr5/CXlNA3W2i5JCbQZUH0/dVodISqOuIi8bGxkkYjmJDsONmgXWQE2XPRDVs13EyvHyyqRxwQvjiNCKaOM54Lu/gGtmTeN2b++1N7p0A6jU6KoyoegJnAQoznak/GPrgixYRNc996c1OQ==,iv:MxteuzCLyqrzJa7uzIdKlCRrNpGjVsw6N4ld4i+v0RY=,tag:6nVcX8SP3Yy0yzNDgr8FIw==,type:str]
sops:
    lastmodified: "2026-04-14T12:34:13Z"
    mac: ENC[AES256_GCM,data:MJjXRMV87d8pMh8BiUA/9crKjwdWrMUQyPDvNA6+jUFpuOKmlz8ktnp11D+VZfoOEef3pbxhlp2dxQugBLnrCn/B+Wd19d3jxRSNR1LUntgtEuIgs9lv3eqOwPlY611hJjTb3pDXDr9279gOwChJwr7JnqS7cC/xyblxC+SkQig=,iv:qW2ucbpMZhBSKRzw0ce9J327Cl0o17I41iMshZr9PPE=,tag:0kpXGPInDTibl4HQRuxt1g==,type:str]
    pgp:
        - created_at: "2023-05-18T17:20:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8WjeZLD+fxwAQ/9HJ8VoZz6RUQxbfVc9fWwzzSVBNi3BeFq81Pxt7uNzHBD
            d1JFePTLaXAiRX8+dVcFs1+KOkArGkSU/qP1Okbp82BmWQRZwq4SQilvoXvSItqT
            BfDxvD2WBBlMzxnaX4wpLsCHzClcSj0OiUzzHhzpIZzNP8NDVPIyofQSPBk7OKAU
            okVR0rjuaVyqdUSbyaPFI5NayLMWjO/VLIpZfiGsGi4i+Wvj5NiYPoafrcAc53oe
            /oCBL1W75eF/FzFiv1bMj5uRxM7Jc6+Ij8hfxpkkubu6pOrPCnNIPxWuJeJuOT66
            gDW7VTmOFyqqV7zUKjDoO6aFKRnOwc5ZfLxhPBdTzkpiB1cietRcoQCdsWHvKL2Z
            MDrzEgmMSoTyAPFnPhoioJ2egeOM4v8Eu+QrHkya8wL14Ur7eWCzE6P4R17dJxVf
            ZrSqzWiMVOUX+AewuBGH3cZaB9qpZOhf+j3jFEwINB+QfxEz9Dqi7+GWOfZu08/q
            TURJ9XnnIJZ8I6lggRW1Kyb1WUbT199x8qFEUljEf1DnQaN02UD8N0bedtgJu2Q6
            o5M61ehrrya9FN3oESBFH6uUxacFr8EeMoC+LbdXuUfYrn/pzj7GCR7MXtWn7z4e
            fOuyStgGCSjr+EewwuXn+9HkkroUQbiDfsiQFZti1Dtt8xuwENN+Auie9f7SaiTS
            UQHTPUNGnhXy7kFCS2zr1kcIiHbEt0JXmWGSksuoD7rpLpnwdQEC10eKbtWrkcIE
            RG8TE6PiclF8Kh84DDwGwQmd88jFd5aqh3g1Vh/mDSabKg==
            =fJ5P
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
