apiVersion: apps/v1
kind: Deployment
metadata:
  name: homectl-next
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: "homectl-next-settings"
spec:
  selector:
    matchLabels:
      app: homectl-next
  template:
    metadata:
      labels:
        app: homectl-next
    spec:
      volumes:
        - name: homectl-next-settings
          secret:
            secretName: homectl-next-settings

      containers:
        - name: homectl-server
          image: ghcr.io/fruitiex/homectl-next:main@sha256:df7a6cd4878b3301b9a5a037b8d6e97e2cfc8b426763715aa4556b1ddf02a157
          env:
            - name: TZ
              value: Europe/Helsinki
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /app/.env
              name: homectl-next-settings
              subPath: .env
