apiVersion: v1
kind: Service
metadata:
  name: homectl-next
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: homectl-next
  ports:
  - name: homectl-next
    protocol: TCP
    port: 80
    targetPort: 3000