server:
    ingress:
        main:
            tls:
                - secretName: ENC[AES256_GCM,data:7nXsjP0srBuz9cOzoptWog==,iv:yNw/SG3wm9MygDnpsqpGiE9f3VbJidERXUBQdPIsFo8=,tag:0Pfek3r9/eNd+XaWPN741g==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:L1z4sRF1/lZkJe55PMfSfWAHDQ==,iv:8HFFd8EHHr0pSY8tzt3pIr9eslpyb/tFDNvA9YowOck=,tag:a50PnksunooMnp3YZ4pcvA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:obnmzWd3foWy/A4yx0ij0UJCew==,iv:SLhEKDMgIwe4M47kjYk+4KuFQDrJVZSRZL+3v3DBYK4=,tag:sxFm+IWedPbF6HPJtjnbww==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:OA==,iv:4wZh3PQt34LPlLWB8cHdWBlGU/Bfg6UsEmVP73Xd9/o=,tag:QHqBb2oNrtA8N3bKyeEX5g==,type:str]
                      pathType: ENC[AES256_GCM,data:sptcsw/OQE3gDDaSx0GyBWe0v2h9iQ==,iv:vASf55JFnpBgmWzZqPOlzVzh4IN4IYNkK/r807vdoZY=,tag:PxUYL3Z+oYUs1ZSR7xiiaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-08T17:50:39Z"
    mac: ENC[AES256_GCM,data:k0GaN9VFWipCFAJi3MTtUBdeTX5ezVh0Si3mgWwfbPuFb0CqMlpIoRe0Q7ohBvlil68AzUMZL7949+kthz1jea6S7tK63zmt8/E9MiUy3sA+QnhlTb7+It7e52IvsjCpw6GbILa8pT8+iyFL3JtrSxtf+x9nTflpBshejuRLujE=,iv:qEnTev7owj+lNCmc+82unGAd/iU1815eZewfCaP7M8g=,tag:Ej9JZXwDWHOAOaPgW740Gg==,type:str]
    pgp:
        - created_at: "2025-07-08T17:50:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8WjeZLD+fxwAQ/8CcJ1HFHStZoYUXsQcdEjtMWo9XvB7SNxR+XSqHHK2T39
            3H9qJTMN7yWJ/OFGIyQ7OIDu9dYYCEWCxa7EpGMo5Xi3wzz+3FUx9uf4Oa8Zs+vS
            24YFHr9Sf1Gasr9xyGKeXmtSImewTSbtqcZzyVgkm6o29ocJ6N9DB6oVIqK079EP
            MYLLUOytlwPWQC9O0qmVwINEuVkr516gmKagitcz2bpsYPVqmVux3otRBb1xyWIx
            N4pPM0JnErQQp1mXE8rshcFTOswvtcTEm/OAdxgXBI8ymzRG/8ssijSYIykSQcit
            aQKeTtF51EDE3syUVN/VePY7mJrtCOe8hdq3zppeHHKm9KyoslBtW6xBBWCyB0if
            bW/7z0vD9ABCy7oTIxmIREaKCqsvQvA/RYGe/HkMIc8ZLxiY4VG8xvpJn3vwqOw/
            IDde7gAV9O1dszyhyyIhuFU9u81LIRlqLKk+OjhOICGrQC3OP0IOgvGjoD9aJPBp
            iMiJkvK7KMDAK/+eR+WPI6A9RGEJ2JseCIxECFKMhZg04msyDTeqJc7pk9XQn2Vk
            Yl9LyehY2dh3Ut7HOMr7kjWkgWG//FMBQGtg4e6XWLrkkJr5WpazlrWz0M8Q7KW8
            tZ/qtA5K4jSqFJZ9gxO6gA0+kCUNoXoGrV1LF3YbHtODjJr0SWRBEf1S4ElmVVvS
            UQFWdIK8Ha9LKsWxdCsI5a6nr2pZoHyW1x+Bsb8CA8oIIqDE7l6fiXcomnN4AgoA
            C+LHejwjI9o+hkF9MQJ29g1nzpIMPOYdBQGFaJSTtBFmNQ==
            =rOz3
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ingress
    version: 3.9.2
