apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./immich-postgres-config.yaml
  - ./immich-postgres.yaml
  - ./release.yaml
  - ./volume.yaml
secretGenerator:
  - name: immich-secret-values
    namespace: default
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true