apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: default
spec:
  interval: 99999h
  timeout: 5m
  chart:
    spec:
      chart: charts/immich
      sourceRef:
        kind: GitRepository
        name: immich-git
        namespace: flux-system
  values:
    image:
      tag: v2.0.0
    env:
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich-postgres.fruitiex.org
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-config
            key: DB_USERNAME
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-config
            key: DB_PASSWORD
      DB_PORT: "5432"
    envFrom:
      - secretRef:
          name: immich-postgres-config
    # Using unreleased chart from git with valkey subchart instead of redis
    valkey:
      enabled: true
      image:
        repository: docker.io/valkey/valkey
        tag: 8.0-alpine
      persistence:
        data:
          enabled: true
          existingClaim: immich-valkey
    server:
      envFrom:
        - secretRef:
            name: immich-postgres-config
      persistence:
        external:
          enabled: true
          existingClaim: pvc-immich-media
      ingress:
        main:
          enabled: true
          ingressClassName: public
          annotations:
            external-dns.alpha.kubernetes.io/exclude: "true"
    immich:
      persistence:
        library:
          enabled: true
          accessMode: ReadWriteMany
          size: 10Gi
          storageClass: nfs-csi
          existingClaim: immich-library
  valuesFrom:
    - kind: Secret
      name: immich-secret-values
