apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: default
spec:
  interval: 99999h
  timeout: 5m
  chart:
    spec:
      chart: immich
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  values:
    image:
      tag: v1.134.0
    redis:
      enabled: true
      master:
        resources:
          requests:
            memory: 300Mi
          limits:
            memory: 512Mi
    env:
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich-postgres.fruitiex.org
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-config
            key: DB_USERNAME
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-config
            key: DB_PASSWORD
      DB_PORT: "5432"
    envFrom:
      - secretRef:
          name: immich-postgres-config
    postgresql:
      global:
        postgresql:
          auth:
            existingSecret: 
    machine-learning:
      persistence:
        external:
          enabled: true
          existingClaim: pvc-immich-media
    server:
      envFrom:
        - secretRef:
            name: immich-postgres-config
      persistence:
        external:
          enabled: true
          existingClaim: pvc-immich-media
      ingress:
        main:
          enabled: true
          ingressClassName: public
          annotations:
            external-dns.alpha.kubernetes.io/exclude: "true"
    immich:
      persistence:
        library:
          enabled: true
          accessMode: ReadWriteMany
          size: 10Gi
          storageClass: nfs-csi
          existingClaim: immich-library
  valuesFrom:
    - kind: Secret
      name: immich-secret-values