---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-immich-media
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: nectarine.internal.fruitiex.org/volume3/photo
    volumeAttributes:
      server: nectarine.internal.fruitiex.org
      share: /volume3
      subDir: photo
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-immich-media
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-immich-media
  storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   annotations:
#     pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
#   name: pv-jellyfin-photo
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: nfs-csi
#   mountOptions:
#     - nfsvers=4.1
#   csi:
#     driver: nfs.csi.k8s.io
#     # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
#     # make sure this value is unique for every share in the cluster
#     volumeHandle: nectarine.internal.fruitiex.org/volume3/photo
#     volumeAttributes:
#       server: nectarine.internal.fruitiex.org
#       share: /volume3
#       subDir: photo
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: pvc-jellyfin-photo
#   namespace: default
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
#   volumeName: pv-jellyfin-photo
#   storageClassName: nfs-csi