apiVersion: v1
kind: Service
metadata:
  name: bambuddy-service
  namespace: default
spec:
  selector:
    app: bambuddy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP