apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forkbasket-data
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: syno-storage
  resources:
    requests:
      storage: 5Gi
