apiVersion: v1
kind: Secret
metadata:
    name: forkbasket-server-env
stringData:
    FORKBASKET_SECRET_KEY: ENC[AES256_GCM,data:vY1MR7q9WdhabuDVnTmOo6qwHfEtEwAHFrBALx+tmHq/lSB8OBWj5U5+jHlW3r6kZjKzrbXKFoFy075pEmt3jw==,iv:HXkVnl8OE9MFahssL5yRU9pUXfQdqln+XeajtSf9pfI=,tag:zGS5tTTzj3Ll052bqhoJpA==,type:str]
    FORKBASKET_SETUP_TOKEN: ENC[AES256_GCM,data:YJ8oLgl/FrrBZL6QjeJwRNa6u8rzjDqvD5D6SVOujbzt8aAKyfh30nZt3FI9fVPIAbXOOobvzusXiDJWT/dOlQ==,iv:mKsf3Q2hb8kxGQLnEshYYnj2YYB+RFXWLH3gkC5adB0=,tag:xqGBEsvw6kQTRhNZZlqGmw==,type:str]
type: Opaque
sops:
    lastmodified: "2026-10-01T05:43:21Z"
    mac: ENC[AES256_GCM,data:LO4tc2Z1L5uVAd8sPzHri2ihy7aBZwKREZi1qQ8AAY0vYOi7qiU1f/50Pi9zckqXczjtjYHCshDhFxvwt8lz/ZH8MwQrpJiWT/iLmyPJLh5t+OChyLYuGNiM789PRNVrm1UukxQWgohKC+WGdR7bCapcnggT4H8WuhPmYgrlbVQ=,iv:xlr4gfbybe2UHFpvqXv2Y9n/+K6i+vJOgzqkhKkqU3E=,tag:id0z7axRf94IxIV3qfpcTA==,type:str]
    pgp:
        - created_at: "2026-10-01T05:43:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8WjeZLD+fxwARAAvEe9rPyet6LU99BjouSV02yg7qda57hlGlsb0mTBKOQc
            OBJhkKwOsEVUBVokGU02JrmE6o1vcvy33qWhex368FEjR42ao6d5xJKuLPQqBbAv
            C32Bn8m4BGjeqOOkSVzOM3gj9yrPk6kAHcb9E86IE6sgRijDKb/94aKkvt4TwS5E
            NrBuedswKTAlmjmtsj/USVF1hDgXCVd7MvCjJY/93TnloYck4TalYOtUsLsIzLcF
            BlxXPDG7OlOXfJ5you6MEacT5dbBbKlkribBkiVst3Zs6gXBckNakJ+SjmOYU9vS
            gw5qr7ADFJK88wFuBl8APOaG9kcKSGYOoqtR9S5tGnusxEL1P6maqmZVqfdrvMDT
            8tk4SsjNmjGvgBYzZNK7g9kdmkXYUisVMionvsMIgxWqrV8+vwi8glfD5tsPmJOM
            XpB3IuvPr1osxLv6fP5rBSaI82YMJva4HFVi4NQYO7R1EeLA4Pvay52Q9pNn/R/w
            x02QM+24xtgtZOiz2Nm7y9pOvSme+aphPBACqJhhgfvxQwegG49+cWv9kJFCG04A
            fCd26KDJU4VpsGLDnbk3ddzLB5Xfnny2jAsNzojrPfbJBRU7+FdYRYh19Bj6WWZi
            95kuRjmpyh6vlWzLKv16E+v0nOiZeMKm5RXcSxYPIBV0fChgnkr8LqMbbReNGQLS
            XgF7KR1/cgKWPCwTZkJqXo7Zgc6XxOnPSUCQfQasIh+wYGCfPGvrv1Nx2X2lYcoF
            l+yiHgJiN4dPM3NTOMJMDicW4ti/FDKDnBrt85ec7oZDV6OPhHB+L0QIV3zAt4Y=
            =QQbz
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
