apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chores-data-nfs
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
