apiVersion: v1
kind: Service
metadata:
  name: fruitiex-org
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: fruitiex-org
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fruitiex-org-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: ${LETSENCRYPT_CLUSTER_ISSUER}
    external-dns.alpha.kubernetes.io/exclude: 'true'
spec:
  ingressClassName: public
  tls:
    - hosts:
        - fruitiex.org
      secretName: fruitiex-org-tls
  rules:
    - host: fruitiex.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fruitiex-org
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-fruitiex-org-ingress
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/exclude: 'true'
spec:
  ingressClassName: public
  tls:
    - hosts:
        - www.fruitiex.org
      secretName: fruitiex-org-wildcard-crt
  rules:
    - host: www.fruitiex.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fruitiex-org
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lovegren-fi-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: ${LETSENCRYPT_CLUSTER_ISSUER}
spec:
  ingressClassName: public
  tls:
    - hosts:
        - lovegren.fi
      secretName: lovegren-fi-tls
  rules:
    - host: lovegren.fi
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fruitiex-org
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruitiex-org
  namespace: default
spec:
  selector:
    matchLabels:
      app: fruitiex-org
  template:
    metadata:
      labels:
        app: fruitiex-org
    spec:
      containers:
        - name: fruitiex-org
          image: ghcr.io/fruitiex/fruitiex.org:main@sha256:9a04109a629af43fbe2fad1102f4bafc9f0ee07fe792992ffebd6dc3d13ef280
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
