apiVersion: v1
kind: Service
metadata:
  name: fruitiex-org
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: fruitiex-org
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fruitiex-org-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: ${LETSENCRYPT_CLUSTER_ISSUER}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fruitiex.org
        - lovegren.fi
      secretName: fruitiex-org-tls
  rules:
    - host: fruitiex.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fruitiex-org
                port:
                  number: 80
    - host: lovegren.fi
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fruitiex-org
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruitiex-org
  namespace: default
spec:
  selector:
    matchLabels:
      app: fruitiex-org
  template:
    metadata:
      labels:
        app: fruitiex-org
    spec:
      containers:
        - name: fruitiex-org
          image: fruitiex/fruitiex.org:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
