apiVersion: v1
kind: Service
metadata:
  name: fruitiex-org
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: fruitiex-org
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fruitiex-org
  namespace: default
spec:
  parentRefs:
    - name: public
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - fruitiex.org
    - www.fruitiex.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: fruitiex-org
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lovegren-fi
  namespace: default
spec:
  parentRefs:
    - name: public
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - lovegren.fi
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: fruitiex-org
          port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruitiex-org
  namespace: default
spec:
  selector:
    matchLabels:
      app: fruitiex-org
  template:
    metadata:
      labels:
        app: fruitiex-org
    spec:
      containers:
        - name: fruitiex-org
          image: ghcr.io/fruitiex/fruitiex.org:main@sha256:fe34bc76ad2f876dcfc8e601ea1518db7fb8caa01fd6b60bc580698f10c813e3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
