apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 10m
  timeout: 1m
  chart:
    spec:
      chart: metrics-server
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  values:
    apiService:
      insecureSkipTLSVerify: true
