apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mqtt.fruitiex.org
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: websocket
    protocol: TCP
    port: 9001
    targetPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: default
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0@sha256:8b396cec28cd5e8e1a3aba1d9abdbddd42c454c80f703e77c1bec56e152fa54e
          command: ["mosquitto"]
          args: ["-c", "/mosquitto-no-auth.conf"]
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 9001
              name: websocket
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
---