apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mqtt.fruitiex.org
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: default
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0@sha256:6e957b3dffe57afa895bed1e311db6f786eb93de70519df2dc81ef77ad6a21d3
          command: ["mosquitto"]
          args: ["-c", "/mosquitto-no-auth.conf"]
          ports:
            - containerPort: 1883
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
---