apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.22.0@sha256:5fdcaf7deb5c158f93a1fc6fe169cdff4cfb9ae0172bee1a90ab0ef74fb9c9cf
          args:
            - --source=service
            - --source=gateway-httproute
            - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
            - --domain-filter=fruitiex.org
            - --domain-filter=lovegren.fi
            - --provider=cloudflare
            - --policy=sync
            - --cloudflare-dns-records-per-page=5000
          env:
            - name: CF_API_EMAIL
              value: ${CLOUDFLARE_EMAIL}
            - name: CF_API_TOKEN
              value: ${EXTERNAL_DNS_CLOUDFLARE_API_TOKEN}
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
