apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-bot
  namespace: default
spec:
  selector:
    matchLabels:
      app: add-bot
  template:
    metadata:
      labels:
        app: add-bot
    spec:
      containers:
        - name: add-bot
          image: fruitiex/add-bot:latest
          env:
            - name: ADD_BOT_TOKEN
              value: ${ADD_BOT_TOKEN}
          command: ["add-bot"]
          args: ["--tz", "Europe/Helsinki"]
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
