apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: add-bot-data
  namespace: default
spec:
  storageClassName: homelab-nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-bot
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: add-bot
  template:
    metadata:
      labels:
        app: add-bot
    spec:
      containers:
        - name: add-bot
          image: ghcr.io/fruitiex/add-bot-rs:0.3.0@sha256:639f58dde980479cbfb073ea273c18b6461f3341f2c8e4edad155704e2f1478e
          env:
            - name: TELOXIDE_TOKEN
              value: ${ADD_BOT_TOKEN}
          command: ["add-bot"]
          args: ["--tz", "Europe/Helsinki"]
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: add-bot-data
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
      volumes:
        - name: add-bot-data
          persistentVolumeClaim:
            claimName: add-bot-data
