apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: add-bot-data
  namespace: default
spec:
  storageClassName: homelab-nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-bot
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: add-bot
  template:
    metadata:
      labels:
        app: add-bot
    spec:
      containers:
        - name: add-bot
          image: ghcr.io/fruitiex/add-bot-rs:0.7.1@sha256:5e598ed26c7e1a1f7b852738fa3903e5ddfdccf5ce22bebf6ebd716e4014e602
          command: ["add-bot"]
          args: ["--tz", "Europe/Helsinki"]
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: add-bot-data
            - mountPath: /app/Settings.toml
              name: add-bot-config
              subPath: Settings.toml
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
      volumes:
        - name: add-bot-data
          persistentVolumeClaim:
            claimName: add-bot-data
        - name: add-bot-config
          secret:
            secretName: add-bot-config
