apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: add-bot-data
  namespace: default
spec:
  storageClassName: homelab-nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-51cb2ddf-a3fa-442b-81e5-cbbb02e2978d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-bot
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: add-bot
  template:
    metadata:
      labels:
        app: add-bot
    spec:
      containers:
        - name: add-bot
          image: ghcr.io/fruitiex/add-bot-rs:main@sha256:24acfd6a392b3e9f89b190a11280b3f6bbf56f1ec7ba465889ddf69f9faf96bf
          command: ["add-bot"]
          args: ["--tz", "Europe/Helsinki"]
          workingDir: /app
          volumeMounts:
            # - mountPath: /app
            #   name: add-bot-data
            - mountPath: /app/Settings.toml
              name: add-bot-config
              subPath: Settings.toml
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
      volumes:
        # - name: add-bot-data
        #   persistentVolumeClaim:
        #     claimName: add-bot-data
        - name: add-bot-config
          secret:
            secretName: add-bot-config
