apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: add-bot-config
type: Opaque
stringData:
    Settings.toml: ENC[AES256_GCM,data:tEBq8fcwTEJSUCKFbU6RK/usDll51pgRvaPn0OEidKGwrQOCU8mRl6UKeRjZEF1nkGjAco08s0WQliHsKvfA8Qjn/gFI1xhRW2tNlOxZdC0G+UOXIOcb/HO+4KQmrCvrmXqxkJHpsGUX/dzHm7Ck5RUYlvV+6sA9sFSmyf4h1a8+qJWCL354gh3TTXjQMfRPhSnwAKx5PBsi1m/xYCDccInZ+EX5AyAbrdM9tvkWRiqcFcemmDq+FpeAH1h33X/tm1O2/x3KV+i8wALaTMJfNhFkiRl1dDeAOxb8967wW6S7JRRGbUXjBcrkEkj8DsLkJsCsPu2mf7hQ5DFEQxZYgvxBvdoto81uRGraunlk2RZK/sXfGGhRLqYFSwmiC01BiRzY2+uMrGarU3NnuCOguI7ObHGm8iSrRfiKYSr1nyUmMwJccHTLqD5vGc7lU3T6vwP506gpP13dz2zaGUT2ZkL1AC1O6eXQwGhQELvkPLO44pDOiQBkJPne+aoRVO+K5J0Srg5qL8z4gWDqUJw+VuVK3GXlPLyBtSDWSHfgkyomfYFg+EW8fW9TC1rjrATAVqVF9phJYJ2vXc6OdRg2ue6qupXfVKmRP3BftX6hZgME2CJ9hJmfDtpf5s07t7SgrmHQ5c7d62mLcfxTSu+SOm4DEnCwo97l1jsPAROdyaMtxShxslT1sJwkm1IY+QnB1fPyBECTtTLUHaYCXHnnUaSAhPO45iWRt7BCR7qWwuMK0BWovz8o4vOtCoiyFXGYFtPGZGQqkbFQR0rX6eIDrb4wZBH+xrFkR05tafYISLS8iGMcAeHXfK6FdiGnrdr8A5YpJrhI7yrU0l+876gomUT4VZIQIwSkzb3vY7do2Nme0PvMqQbLqzsArlWFQEEPyk5/bSBAbX5t8SpFwDFENXfM//qzAbKPEjVfm25KyILlXy2uIaP7sEel88YLtJqOdcK54xlc7YyhT5XfCqnaM9yNRUbFnun2JCiJtRRDsV/Qn69AKytzIMqFTIEcBPeiOP2XGSNSwm88vv/ac/WYg0e6cC5Z8dkCvMEsRClnOa0kOVrDocVKBcXt3os=,iv:aAe9HwYmxjGNMzZeDRaylc7xbJBH0gQ0sPR6Hw47f9Q=,tag:LwF3Tvn3XGbIHN++5PeaVQ==,type:str]
sops:
    lastmodified: "2026-05-08T18:07:34Z"
    mac: ENC[AES256_GCM,data:RB9/3cfBJ6SzDxgJ6GcnhXhIXBoDFjO4JVFQ2NKMkh6DEjUmuaa6EcMdFP0y0M3bMrQzAhbDX2UVGrimD8h8If+YGbb5SuzU/Iz1F3vLQFexZZ7Qw7F6/hMZeUv7vwzfhAtEuAmku9dKb+jZBUWRG0JFPCP9iGU4Af8NHNG9pk8=,iv:yW5o/CIvK/DJAcbJZebiU3xs+UeJPFx3KFxzPiLX3Io=,tag:feiRD1YYwFKEs8v0MqTTiA==,type:str]
    pgp:
        - created_at: "2024-01-02T17:05:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8WjeZLD+fxwARAAk+1/aVR91pXlN5+fkCdsG5zig86JQws0kRr/SL2rKrk/
            P9yAQQZEoercFuz3nurzfE7I1c3UeKy7UixuvyakBjCZbtFZgfjUlNwSluupNxAm
            YAIg+vLJqGWi6IZwALbJRJMRwVxww64y4QZVgAkOCpJwsZ3WB0DlJwP6gWktqouz
            NE6o/p0e3gZDpl7dlkGEYyldu/QBceu6518lqbwzvEt9v/VEzn2dlLOt3juYVl7C
            USgbaHbE21ShLKKirdDMwolEhc6Zs6vTgEPkQCbDIBvMMkEIFuy+58vx2F9OqyDo
            dXIluUz54YlPBLmsMMDcSQQwCLKDORmz7aJR7iJo3RjizBrDhvVOVXged/gZdyQT
            FLWpM1e1JRKLAiGXJ/cmouXRoEpAmeLnScOANfrN6QkTrbTb95oVTsSMFg9uR8af
            jixG4iPRU9FPfbB6sAWmDWmrj4HneCTpaROTOw+u8/38upzKdq26sBJJt3UStTdS
            v9fJL6zmWToBkTwGafbJFPOZq1XvXvgDgMuD7uTLc+zTibpX9yWoLLbch/GPQYPT
            V6y08hHQ9vo06JzNGX3hol3tPO9Xw0LfkWxPz9hk6G/pveAQkTByvPJ2uoJwWL4t
            2/H5h2IZ32SyOb2sY43As3rLiNqvQK+dpkoIg2Tq+Zusg1/zjagtcLx644i2ClvS
            UQHee4h2EfMMT7DF75we3V3CIX84nmeAC1JRFyTwMZFKE132sTIq6JHkit4sopkH
            9I8Ej7tOhZYpqtH//NJ0tdOabhqYgVr59vVKUvauRw1n2w==
            =wSX1
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
