apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: add-bot-config
type: Opaque
stringData:
    Settings.toml: ENC[AES256_GCM,data:R8i8BP5Zh4bWZ/vHCCUN7tbdMl+Gd5TdZKvnhLorx9f9rxoMPN+ugAAR0ST1hGZAreuvDNVFd+O2Pp3yTVI30+hr8O5gp8DSrjEkJGlSV6rwmWkCLoeo27WVnIC+PgrCjbxahAO7M2e60Ub4cqBWdu2vEyfAEFdrcwWkzwaHRleYYiAOn5FDGr3XVBtYrOXgizMbjVZDJZbxGEluncKhbIgFqAuRmSlPAQDtrZOE2yteDznHssGMmMcWA7m+aP4IuSEWA81KLSIxPjyObr1SZI5lgfbMM22PQIKSrSw3HDODgbTb/gAlc/TrS3KKV1lMD8R1SMJR8iQU3zu3TiP9Nn3sCtPtjEI5RsAW9IOxjD3XrbYGhzp9kGA49HqSFio4qx/nnsPgvkHwMVTxmzbnSMV7Jn/ONK2+qWxVjsoTPUMubFTEvtgAiT1tOSK+ncjsyBrAZ1GL8nXJqy05ILht41pUJk++sn9hpeKglfUZjMua5+F9dpk2+IZ+abcj8fb/iY0gQqp9L2jQf82eIap8zYA4bkIs4iQNsgBbFT7ZUfz7R+5hjT0ZBsunjCsleXaMfHgcfPqsRG+wlFYUo4e4/TxvMJFN8wbcndkWoSEwtEPJkPL5oCy30ivOu6UQafZ866NIRhUymDy+pW2C3tmPZGdkDiol05DFZeF4S+IdS/lMwLL6A/aA2HGTsb9/WKUmbpQrRQslja5IxmNjvPbJt/whYkNnQrPwOmnidgKLEAjN+biSiLbfB9ZXCO+/h+lhtRvM68LPBU9gZq3pw2EkJF4vNSbxqvs+U5WKV/ct7D7n/FU/Qu7bR+YNt8O3bgnYk1EESc1LRw3DUAPmsOaVA0eXnvfKWSE8+Q1xilI8RVrRBA03LoOAk4bVZXGT6Jp1R62vidw/JsBjnWSqOPAxqjBE0AfOihNVELYINROjeBAnJyY0mP9QkgkzgDjcV6bfqqTO0SnGusqeDsbN0Z7R70ZwTZAvmbmVzHs3beJzBJyzyNZ5b46nuO38+aritOf2SgKzSuTN1I3/FA/m0J5HPqmX6xzJlMbZZIqBoPGpzHvuwGolTVEtRpukDHQadh50fYyyiVgYGWmVAsGoN80z4kPztaZoi1LcZa3mJbCMdct892AiUkb9CzxUTUkCh5wkPy8l1dk/Og4=,iv:L/M1hoUZw4CVyw8oRlpMyMYSmC2nLoGzWRrut7hjdBk=,tag:AxbCsd57RmumMH9Qxcr3SQ==,type:str]
sops:
    lastmodified: "2026-09-17T14:30:37Z"
    mac: ENC[AES256_GCM,data:v/TIPPWhXLDkWLTMGrZ/J+hyvo5P89dyqz7xw8e8Ko2+DxOY3KtFzwqqbB13mdLcCA6s4PtBjLRAaPG8wqPbAQKjtk40lezFAdh1/rmbcmetkxaZVfJN6+7lQu8uNa45ngBavd2qtkb4N05nZrHWWRvtHxup056HcpWMNvxYmdw=,iv:+DxxdgmJU6uryOWBEKqm91rvwMPscOvZ7z2p69XhUE8=,tag:V3vAd76Ks+oJPSe9ySDDbg==,type:str]
    pgp:
        - created_at: "2024-01-02T17:05:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8WjeZLD+fxwARAAk+1/aVR91pXlN5+fkCdsG5zig86JQws0kRr/SL2rKrk/
            P9yAQQZEoercFuz3nurzfE7I1c3UeKy7UixuvyakBjCZbtFZgfjUlNwSluupNxAm
            YAIg+vLJqGWi6IZwALbJRJMRwVxww64y4QZVgAkOCpJwsZ3WB0DlJwP6gWktqouz
            NE6o/p0e3gZDpl7dlkGEYyldu/QBceu6518lqbwzvEt9v/VEzn2dlLOt3juYVl7C
            USgbaHbE21ShLKKirdDMwolEhc6Zs6vTgEPkQCbDIBvMMkEIFuy+58vx2F9OqyDo
            dXIluUz54YlPBLmsMMDcSQQwCLKDORmz7aJR7iJo3RjizBrDhvVOVXged/gZdyQT
            FLWpM1e1JRKLAiGXJ/cmouXRoEpAmeLnScOANfrN6QkTrbTb95oVTsSMFg9uR8af
            jixG4iPRU9FPfbB6sAWmDWmrj4HneCTpaROTOw+u8/38upzKdq26sBJJt3UStTdS
            v9fJL6zmWToBkTwGafbJFPOZq1XvXvgDgMuD7uTLc+zTibpX9yWoLLbch/GPQYPT
            V6y08hHQ9vo06JzNGX3hol3tPO9Xw0LfkWxPz9hk6G/pveAQkTByvPJ2uoJwWL4t
            2/H5h2IZ32SyOb2sY43As3rLiNqvQK+dpkoIg2Tq+Zusg1/zjagtcLx644i2ClvS
            UQHee4h2EfMMT7DF75we3V3CIX84nmeAC1JRFyTwMZFKE132sTIq6JHkit4sopkH
            9I8Ej7tOhZYpqtH//NJ0tdOabhqYgVr59vVKUvauRw1n2w==
            =wSX1
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
