apiVersion: v1
kind: Secret
metadata:
    name: github-actions-runner
    namespace: arc-runners
type: Opaque
stringData:
    #ENC[AES256_GCM,data:qn1yaEptkZeXgwiFhru+AcMfnHCMlLIdNDCSpqVxFPeTq9O0l1rdO2cZ80Ci9U/fm19LkiMB+cefT3wvQ+I1X9VhaSt4AUE=,iv:Sqx+8NNfb5eRMxRIbMnYSDmqlzhOgL375Ig+YB2oy0Q=,tag:DVZWj7uOg6SqUUTchvqjoA==,type:comment]
    #ENC[AES256_GCM,data:Y7Vgu8yGz9t2RR7zw/U/yQjFXy9s59CMtIuwjstLhO03wdnwE8u+B0TF,iv:JSMVYdbvDkwbXfoOClQ4Ibh74/n9Va0GmTA5jd8qA0o=,tag:JYPMglBCvUVMwUWbAHhXYg==,type:comment]
    github_token: ENC[AES256_GCM,data:XUts/+cRp9jtdDs7D8sdMeDY4EqfREelFO1KReSbcPT3NHFgaLBG1ooe2aViZkzp0mJ4yiplM/dZt5dBA6mgYVJh52thfCze57dM0clKmxuVjJ1N3rAlDPKbw8L9,iv:dV4iWR2I81/pivxdqCWpsKMsfct7BW+izG6FZYjVxbk=,tag:zzp/ViCUOX0gJPu0mVezZA==,type:str]
sops:
    lastmodified: "2026-09-14T18:42:18Z"
    mac: ENC[AES256_GCM,data:ETDL7OcnE70VfymF9JGYpjCn/O1v1g3B20/5mkbde8G5ABLfksehBySQqOASeIWovjHznPlFdvgYa3zYSgp77AcRSIOBrMYhu7CGib4kYkZ4i4Rku6rDWKpFHPw56wH1OVUgDCBs9+DaND9dC0fvt9P1MEHA16KKP3UIbEs6pnE=,iv:nIDq0J0eP39VIv1Y5sb1DJKOVax3CC3fLOHkyd+XzC0=,tag:BxWSW9SkEYmP8hhGErvfIg==,type:str]
    pgp:
        - created_at: "2026-09-14T18:42:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8WjeZLD+fxwAQ/9Htd3xSnaOzTQFpBJ0tG0DcOyYN42pxgCqoQm4QDT8Er/
            bL+XFy+lApjwyrOaHAdNcMUfX47/+x+/er4s+L8Boz7ZWisZUfFmO0+Pi13Xl62L
            KAdMoUVUEN1JNujsOMzsxS+IrepDZylk50RVgEwJVJaJrl2b6bFsCWTf13Co375o
            5ryoNeMZNkxVFBZLuo8bAXopqTGSsyVWrg+IUsPF2HxZMKp45/COSfjxYzef0DMj
            +DB96wSr+XTQnU0CYOMPhX39hJ3gVXEOhl9UOuT7C3LmFIwavZaWMb9AyVRfukPv
            IrHaFbkWQq7eVdyypLbrNytHdkb83hXl0c83l2sRDQMp7fPIKiB6zpUklz5ZqlBv
            OunfDjP0IgHakwl5TJ3kJYgyAwgG/rzHHCaSnog3ywgCEMzkE+02h5P/jesQ1mNd
            gIxXB/AELLpbJksvb2bYIGMeR4++txjuOrbEZO68SAD0quUsJ9m51Gzrf2elnwlH
            QwnCsAE1tXKn8/YhPJY/U7ur4u7TMNMlDFxPvN0IQg/j61Lsu2eH7Pz9BgdtMqW9
            skGwzG5/PsT+NOa3xNuSwtfq31efJD0Bmvpne8LH6AOKORPjMqD+c8kPRBh8VP+r
            z+GiLD6pOjqAVhBOFWcp543ENdJKs2G57ZgFdXB8zsRVDvLmVhfNrl/qJ4Cf96PS
            XgH3s4GmuW+8jJBoATSNbLyBvsacEEL443BCx9NjbLxJbd0PE+JMvnZewykBebDM
            DxyheOQgTyPC1cEiY7jEQyNZ8ilg+9CF1seJky7aV0OCtRI68KW3UF8DQ6eeA2A=
            =ElkF
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
