apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - github-actions-runner-secret.yaml
  - controller-release.yaml
  - runner-release.yaml
  - add-bot-rs-runner-release.yaml
