apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: default
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.fruitiex.org
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - name: psql
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16@sha256:302de9d3235dbab5e89a87f889663116259eb7bce4aaeaaa6a1117daaa9a4750
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
        # - name: postgres-debug
        #   image: postgres:16@sha256:1e90f8560705b0daccbd8eb25573627c8452fc9282496433aab1259ae4c85824
        #   imagePullPolicy: "IfNotPresent"
        #   env:
        #     - name: PGDATA
        #       value: /var/lib/postgresql/data/pgdata
        #   envFrom:
        #     - secretRef:
        #         name: postgres-config
        #   volumeMounts:
        #     - mountPath: /var/lib/postgresql/data
        #       name: postgres-data
        #   resources:
        #     limits:
        #       cpu: 1000m
        #       memory: 512Mi
        #   command: ["sh", "-c"]
        #   args: ["while true; do echo 'debug pod running' && sleep 5; done;"]
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
