apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: podinfo.localdomain
spec:
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9898
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
