apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: podinfo,podinfo.localdomain
spec:
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9898
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: ${LETSENCRYPT_CLUSTER_ISSUER}
spec:
  ingressClassName: public
  tls:
    - hosts:
        - ${PODINFO_DOMAIN_NAME}
      secretName: podinfo-tls
  rules:
    - host: ${PODINFO_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:5.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
