# https://geek-cookbook.funkypenguin.co.nz/kubernetes/loadbalancer/metallb/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader
resources:
  - namespace.yaml
  - release.yaml
