apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 1h
  timeout: 3m
  chart:
    spec:
      chart: reloader
      version: 1.0.22
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
