apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 10m
  timeout: 1m
  chart:
    spec:
      chart: reloader
      version: 1.0.22
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system