apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 24h
  timeout: 3m
  chart:
    spec:
      chart: reflector
      version: 7.0.151
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
