apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 10m
  timeout: 1m
  chart:
    spec:
      chart: reflector
      version: 7.0.151
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system