apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: hue-mqtt-config
type: Opaque
stringData:
    Settings.toml: ENC[AES256_GCM,data:oEUr5W7AwNMB+peoooj32p/H0SWYr3o8z6epff3U1PWe3PU8zX6LDXmPIYgEnlyvcybd0/dN/uC6XyT8OSjZV8y0cRk30dSegcM+EWjt9HhWPhZ52nJ33DGSS76i50EiMJaUIRabJteWZotDpjX6s4z1WVFw9I/wUWG/YWxQNQ7v7qITzhUl9DLs0AKVrMZmzOhhprkhSkNuMq3sjprpD62tLegc/id0xZx2ycWAysK7iOdV/Es2DGohoIK8ekrJyAynInLWhD9CQyRu2m4IS8ytRJNeQbYkh/gvGEchZNvkq93ZlIpg2/pxyeseVnHgmTPiLTG2XEUaEqu2D2rcp0fZyFug8loMPZTaeFRJZwYBd48AFlsxNwjNPn8vI1uMaO0nYXrrFaAV8dmJAbO83WDi/3LLwnAOrF2P4SaobgvkAcq+jprRlHfcSI/yFamiEGy8u0nGQJXCOZ90w30HjjLlEbnqgO2Gau4OvVHqiIScG7pLitQwYmXV0VzrD0XCXjR0ne32MumcKx0ri5BwmHyOpsvejOxzIANCfCOScLP+aKxHIonkG7z/Y3E2eLgmXsdEHaoWrK7dGCbApPBBdGvMYHfML77RnHVx5RdFzM5gKgajokhA7WqFcVwkTSI4tamlxw/UYe2Y5hDnhBhnnOzWs5IdZHIFTNb1CRnmovAkkvKmHi1WKkvps546FQUBo8ewoocEoz81jsiqNLEXug7PF8OWazsCRV80JzWKN3MphIrvUvE1DGMsFPy3cZhVwdTDvUuuIlF8ZQj6Zw057VMgu85Tgw/ylFpGST8iUaP/sdS50Z5uFUcL0+HTadz1+WKm3MsD1CuofQND39hoZulexYk/5yK8HPyvDJxkZxOhKvbuyd4JbO+EQ0XA4OVl0ySShjvPqRBYdGowWRpU3WoWU7GKkoIsTlnucpoG0V+L7wGhOybH5UAKIAdrfsw+rr82o7MMtArhA8zvEGMvIXSxAGNmZ6nXeqL18tVbKZYIulwOybSW/LqDxphOgSgHAU725rFckdj795BJJgeZ4jx2MIq1gIVcRWpBoaHyL5GHKVzrd68OJ5fqhCjZU4//90lWSyYHj72W2avYWJx9qQjJfhGeElmyMSuNNlAMKqhq5UoLUNJ1NWs4Io53TrPrp2CFFDlOZCr60ii8NfSfqaDdq/9selWhqbnE41sG7q2Lk5mPvf/y12K2so5fAfkm2BSux+Iqt1ieBQTLbq9efJMLx8H3tMI9LUuMjVMc43w3aZHmsf7bDMvUtXrzpwHkGKBZBq36PHQiLercBy8+084rPuIIEQ9vPMWcVNji+o4VBoDmAXIME03iauKaHP/TSAtF8zP8pv8RC2kQBjLX2AiWbbOaGtoeNvdYUlVzIMBz5Hb2TE4SKEO3OWcj/SoTr52wMUW46LABI4dIycIkPi7Q1KBTSGvBRQVjgwX4g2LN9LbDXvkJnp/lO63Q/2Qed7SMyhfa0LcUHHDhFw2UtNQ/T/UiWVc+RiKBtIZc8qnJhAut6UL1KtD/uTRZ2iJeObfQ+VhtfSduSG/ymtHJ0UJEKer1+cPX3ElnHxySI8LpcpOeSiM=,iv:jFIOPJMIqvqPpZtqEh3YSGURxUdS8mnQ8fVe2ofqVIc=,tag:Nk/EaUdO4/tpFi17yETQoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-24T13:02:19Z"
    mac: ENC[AES256_GCM,data:z8F55iVDG7X+UbID672S9KUGd++u3a7/jng+LDuddPyXNvNnF4jhWoTeFhTxP7N88SwsksXuBnusI8Xsf24+vrYnAZeW/aA4Oj5Pt25vFKvwH+p5Ebb76VtgFZpCY+kCx0LWmCow/W46c1D61VGAjYlrbZGnKcNBenNiOltyZKg=,iv:LeBKbk/lyFZwb3aVD7/PSZ7hOP/RFaZWqwmiEuuF9Dc=,tag:I1bi28RkmjFUofonTzf46g==,type:str]
    pgp:
        - created_at: "2023-04-06T05:24:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA8WjeZLD+fxwARAAxUEE7kEOhB1dEVwWfbWCnu2wr0KDqIYeJ56JcZmwRz5I
            7fKSL+045LYkbfruO1qKV4E0UAvJ2MJGTey3TrhYAxfkvCpbFRJrzFiyqvmhHISp
            rDdcUfXooR8X2mVO9ndTLNWQiJ60EnbMrzhMRF51J2Bmfjl8g3BQ47RrXcAVQkkf
            k+F6UdrfnIWG2/izcEm3gbngNe3yT5zXoWOMQs5XSTOzu9VPq215iEw363iKjea3
            1gjwAFCtbaK0765oSw93G/tJevtAX9/fYkfB/C6BO1Rr+OqwhKtSyOW9dTRVjWs7
            zXQ+3e/+/7OiAn6q+9R35z8685GZF1S5aFCnrmtj1CImIqQ5fLaBPxZd2sZuLVEq
            7xTRMNEdxyGpYtbPAD3c0kGUpM+aI1INT8occJEl8y9CvtcONPJbyjoXNF+t5UwW
            BsYavGyQcxiK4AAxkHF66uSGvxhJIHRpvb71HK2DaQSX7IBAzhsexTc70qFuvEhd
            MsDLaIjvUd4HYHmc8s/LHWasjglYlB73oOw4NYlMYCDD1vSjtiNTooKd5zxeRrwH
            gkEccv4xEjBmSRWRD+ik0V00H5ULW9CqkDOuaLmme240vO2Q6ubZRfOpInoBa5Vh
            u1QEpV5VmpTfxPF2z86yTZKyfljdoIF/RPn0jjZi1gG2d20TexLDrTxuB49fTLHS
            UQFfkCqWuyEjB+jgfXDND8bmGNahsuDkgviPGrAjKpkzeTfs5Tfonk959ir6VIYG
            t6Ncu193f6uRKYEmH73ymjxpzP6/RoCTWque0CjF6t+X4Q==
            =bxAe
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
