apiVersion: apps/v1
kind: Deployment
metadata:
  name: hue-mqtt
  namespace: default
spec:
  selector:
    matchLabels:
      app: hue-mqtt
  template:
    metadata:
      labels:
        app: hue-mqtt
    spec:
      volumes:
        - name: hue-mqtt-config
          secret:
            secretName: hue-mqtt-config

      containers:
        - name: hue-mqtt
          image: ghcr.io/fruitiex/hue-mqtt:0.2.0@sha256:8008f2625bacf45037048721fd50e395113b8b54f01dbc65ec4bb4f69eda48cc
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: hue-mqtt-config
