apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: loki-stack
spec:
  interval: 10m
  timeout: 1m
  chart:
    spec:
      chart: loki-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      isDefault: false
    grafana:
      sidecar:
        datasources:
          enabled: true
    persistence:
      type: pvc
      enabled: true
      storageClassName: syno-storage
      accessModes:
        - ReadWriteOnce
      size: 10Gi