apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuya-mqtt
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: "tuya-mqtt-config"
spec:
  selector:
    matchLabels:
      app: tuya-mqtt
  template:
    metadata:
      labels:
        app: tuya-mqtt
    spec:
      volumes:
        - name: tuya-mqtt-config
          secret:
            secretName: tuya-mqtt-config

      containers:
        - name: tuya-mqtt
          image: ghcr.io/fruitiex/tuya-mqtt:main@sha256:e24a342906417f7c0261c09d2886659e24fcdeb2eb02f2b511c0337846781b7c
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: tuya-mqtt-config

      initContainers:
        - name: wait-for-mqtt-broker
          image: busybox
          command: ["sh", "-c", "until nc -z mqtt 1883; do echo waiting for mqtt broker; sleep 1; done"]
