apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuya-mqtt
  namespace: default
spec:
  selector:
    matchLabels:
      app: tuya-mqtt
  template:
    metadata:
      labels:
        app: tuya-mqtt
    spec:
      volumes:
        - name: tuya-mqtt-config
          secret:
            secretName: tuya-mqtt-config

      containers:
        - name: tuya-mqtt
          image: ghcr.io/fruitiex/tuya-mqtt:0.2.0@sha256:b879df236a3868457b2384207c09720a130b5bda85d9e5cfc4a7d2e2aaf4c26c
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: tuya-mqtt-config

