apiVersion: apps/v1
kind: Deployment
metadata:
  name: twinkly-mqtt
  namespace: default
spec:
  selector:
    matchLabels:
      app: twinkly-mqtt
  template:
    metadata:
      labels:
        app: twinkly-mqtt
    spec:
      volumes:
        - name: twinkly-mqtt-config
          secret:
            secretName: twinkly-mqtt-config

      containers:
        - name: twinkly-mqtt
          image: ghcr.io/fruitiex/twinkly-mqtt:0.4.0@sha256:271925ae04a50e2d4e5da80c8896a210dbd8eac206ae6940d72d8c6880d2fbf2
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: twinkly-mqtt-config


