apiVersion: apps/v1
kind: Deployment
metadata:
  name: twinkly-mqtt
  namespace: default
spec:
  selector:
    matchLabels:
      app: twinkly-mqtt
  template:
    metadata:
      labels:
        app: twinkly-mqtt
    spec:
      volumes:
        - name: twinkly-mqtt-config
          secret:
            secretName: twinkly-mqtt-config

      containers:
        - name: twinkly-mqtt
          image: ghcr.io/fruitiex/twinkly-mqtt:sha-a6199f4@sha256:467c469f4d8996146c441dc5a0cc958154288b4a337c1ab88f20b6b638b740f5
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: twinkly-mqtt-config


