apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: default
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:ScEu/EeAEqMhEQtb9n2qNjwyrZ75/znx76+nZ09JVZs3PtJ1sA2pkmownggBCsLBFhKx803eNIHMUXZ21QPx5w==,iv:BWfIHU1I/PwBj2cSth82YPhwnTxv7hDsodVY8W3wqGU=,tag:yXyK23JEVem+R3aUc5UHbA==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:nF96cvlOwy5qmycwHvh8VFGL6LkWRTAD1UI0twDePPyjlH3OculSiPDLciCeSTbjqvGwttLz2hKcVIW1VgjqMw==,iv:qfnFSd4Q0hA5LXIIsGhMMlKckBV/DMDRjPqLt74eZzw=,tag:KM4MD0CGtwqtMIoCeq550A==,type:str]
sops:
    lastmodified: "2026-09-26T15:38:03Z"
    mac: ENC[AES256_GCM,data:k0mo6ucwqY7Nrz1HKKCcwWdC7FyDnPvMvB631vYxNDNZc0D73CXN790w4oWyByUvSbLrb0QUKz9+efJdQbTmJmMV1DS4yIkR0xo6OcB9DxJpQwcd5I3n3iI3QznJ1HLbSUKSgwUvOkiZpOmsL6KBTHqhqSSDalVyl5nnFJVnC0A=,iv:tJZQzMORVEVGIaRhQQrLz99/hv9Ql5oojx+P42NEWgY=,tag:JwfQxzFkmWx+pNhp0KpOiA==,type:str]
    pgp:
        - created_at: "2026-09-26T15:38:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8WjeZLD+fxwAQ//VW1ApcBZfQL4eWmYPxmRhbqjBv+muz7J7bxcq2D7Wphg
            PWghOinhbd+ZUDfq7OWHC0a2FyFnD1mOk01aaQ/kvjwDIIngxCNWvbTzr4Vy159y
            /euRpwO90Ng6fBMyS06hI0HGrFWAwHv1SQ6s8AN8rMPJENPcLERbBhoxoP8SUTCZ
            E27oRHRc5lKr7QhJEwxbOskLYC/yTJgDcyiZ5mVLyhbPSVEEbJM1oK04VBVlXKlF
            0UKKbEV9UGN14ph2iYcFFQWE5yWX8pBMm90t231N3XjQyi9NlYo5rH1JVrNrEa7i
            UQJY+6rPQzEmleLBe8LcedceBCSgz38ogsCwBEZTXrUzVGA5S1ZrPyUM+crmy/Mx
            moc3S+frYMwUmuCbmK0fex31ZH63QLFJaDYwsK8iugg6W/WZv+uE7vuF4HLv6wpE
            9rjCxS804FVDXpYZ94lnTcnbuCJ4ipQI5PDOrW6ELQ0B7y10zZQGlHwqCdNP88v6
            DcAcqLJqO4bsgCy8h4IPKs9w9VSBM1hZUcizJlXhCHJSIayztGlaW1jPDVoDp243
            gjo+aX2MlDwuzc4uEcy6zM06y/E904Z983i6UNZ3kvh5+dlkP7psA0GY8D+0Xb30
            Lqhzr1KKZp78evKBnI415+fLnVxnxGE3yxcVH0802FJw78YII006G9KGGpdVgc/S
            XgG2yBpN5obAUhbpBRU7HIEYQkYfl5s49twPSsH+IFXcwhenjGyGFWby5JGf3Uhg
            0TXDzxEDXvyH90C9vVFfmxpFJYkaehoFifMXm+7N4MVl8AuMPKInonq+kGagS68=
            =MOIk
            -----END PGP MESSAGE-----
          fp: 3536F7F9345D96C86FB7F9CD21FAFEE575B18815
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0