apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoframe-rs
  namespace: default
spec:
  selector:
    matchLabels:
      app: photoframe-rs
  template:
    metadata:
      labels:
        app: photoframe-rs
    spec:
      volumes:
        - name: photoframe-rs-config
          persistentVolumeClaim:
            claimName: photoframe-rs-config
      containers:
        - name: photoframe-rs
          image: ghcr.io/fruitiex/photoframe-rs-server:main@sha256:098a6d8731f38889438ab849c44d76b18cf19e962f8c02fba462ea4e682b1c12
          resources:
            limits:
              memory: 256Mi
              cpu: 1000m
          env:
            - name: TZ
              value: Europe/Helsinki
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: photoframe-rs-config