---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photoframe-rs-config
  namespace: default
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
